In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.DataFrame({'Name':['Sourav','Priya','Mansi','Mehak','Isha','Rohan'], 'class':['btech','mca','bcom','mcom','btech','bca'],'rollno':[34,23,11,10,67,89]})
df

     Name  class  rollno
0  Sourav  btech      34
1   Priya    mca      23
2   Mansi   bcom      11
3   Mehak   mcom      10
4    Isha  btech      67
5   Rohan    bca      89

In [3]:
df.loc[:,'class'].str.capitalize()

0    Btech
1      Mca
2     Bcom
3     Mcom
4    Btech
5      Bca
Name: class, dtype: str

In [11]:
df.loc[:,'rollno'] = df.loc[:,'rollno']+2

In [12]:
df

     Name  class  rollno
0  Sourav  btech      38
1   Priya    mca      27
2   Mansi   bcom      15
3   Mehak   mcom      14
4    Isha  btech      71
5   Rohan    bca      93

In [14]:
def funcCap(text):
    return text.capitalize()

In [15]:
df.loc[:,'class']=df.loc[:,'class'].apply(funcCap) # series

In [16]:
df

     Name  class  rollno
0  Sourav  Btech      38
1   Priya    Mca      27
2   Mansi   Bcom      15
3   Mehak   Mcom      14
4    Isha  Btech      71
5   Rohan    Bca      93

In [19]:
df.map(lambda x: str(x)+' hi')

        Name     class rollno
0  Sourav hi  Btech hi  38 hi
1   Priya hi    Mca hi  27 hi
2   Mansi hi   Bcom hi  15 hi
3   Mehak hi   Mcom hi  14 hi
4    Isha hi  Btech hi  71 hi
5   Rohan hi    Bca hi  93 hi

In [20]:
df.applymap(lambda x: str(x)+' hi')

AttributeError: 'DataFrame' object has no attribute 'applymap'

In [24]:
data=pd.read_csv('Titanic_Dataset.csv')
data

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,0,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,1,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,0,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,0,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,1,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
413,1305,0,3,"Spector, Mr. Woolf",male,NaN,0,0,A.5. 3236,8.0500,NaN,S
414,1306,1,1,"Oliva y Ocana, Dona. Fermina",female,39.0,0,0,PC 17758,108.9000,C105,C
415,1307,0,3,"Saether, Mr. Simon Sivertsen",male,38.5,0,0,SOTON/O.Q. 3101262,7.2500,NaN,S
416,1308,0,3,"Ware, Mr. Frederick",male,NaN,0,0,359309,8.0500,NaN,S
417,1309,0,3,"Peter, Master. Michael J",male,NaN,1,1,2668,22.3583,NaN,C

In [27]:
data.Survived.value_counts()

Survived
0    266
1    152
Name: count, dtype: int64

In [33]:
data.Survived = data.Survived.map({0:'Not Survived',1:'Survived'})

In [34]:
data

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,Not Survived,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,Survived,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,Not Survived,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,Not Survived,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,Survived,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
413,1305,Not Survived,3,"Spector, Mr. Woolf",male,NaN,0,0,A.5. 3236,8.0500,NaN,S
414,1306,Survived,1,"Oliva y Ocana, Dona. Fermina",female,39.0,0,0,PC 17758,108.9000,C105,C
415,1307,Not Survived,3,"Saether, Mr. Simon Sivertsen",male,38.5,0,0,SOTON/O.Q. 3101262,7.2500,NaN,S
416,1308,Not Survived,3,"Ware, Mr. Frederick",male,NaN,0,0,359309,8.0500,NaN,S
417,1309,Not Survived,3,"Peter, Master. Michael J",male,NaN,1,1,2668,22.3583,NaN,C

In [35]:
pd.get_dummies(data.Pclass, dtype='int')

     1  2  3
0    0  0  1
1    0  0  1
2    0  1  0
3    0  0  1
4    0  0  1
..  .. .. ..
413  0  0  1
414  1  0  0
415  0  0  1
416  0  0  1
417  0  0  1

[418 rows x 3 columns]

In [39]:
data.loc[:,[1,2,3]]=pd.get_dummies(data.Pclass, dtype='int')

In [40]:
data

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,1,2,3
0,892,Not Survived,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q,0,0,1
1,893,Survived,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S,0,0,1
2,894,Not Survived,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q,0,1,0
3,895,Not Survived,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S,0,0,1
4,896,Survived,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
413,1305,Not Survived,3,"Spector, Mr. Woolf",male,NaN,0,0,A.5. 3236,8.0500,NaN,S,0,0,1
414,1306,Survived,1,"Oliva y Ocana, Dona. Fermina",female,39.0,0,0,PC 17758,108.9000,C105,C,1,0,0
415,1307,Not Survived,3,"Saether, Mr. Simon Sivertsen",male,38.5,0,0,SOTON/O.Q. 3101262,7.2500,NaN,S,0,0,1
416,1308,Not Survived,3,"Ware, Mr. Frederick",male,NaN,0,0,359309,8.0500,NaN,S,0,0,1
417,1309,Not Survived,3,"Peter, Master. Michael J",male,NaN,1,1,2668,22.3583,NaN,C,0,0,1

In [41]:
data.rename(columns={1:'Pclass1',2:'Pclass2',3:'Pclass3'}, inplace=True)

In [42]:
data

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Pclass1,Pclass2,Pclass3
0,892,Not Survived,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q,0,0,1
1,893,Survived,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S,0,0,1
2,894,Not Survived,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q,0,1,0
3,895,Not Survived,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S,0,0,1
4,896,Survived,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
413,1305,Not Survived,3,"Spector, Mr. Woolf",male,NaN,0,0,A.5. 3236,8.0500,NaN,S,0,0,1
414,1306,Survived,1,"Oliva y Ocana, Dona. Fermina",female,39.0,0,0,PC 17758,108.9000,C105,C,1,0,0
415,1307,Not Survived,3,"Saether, Mr. Simon Sivertsen",male,38.5,0,0,SOTON/O.Q. 3101262,7.2500,NaN,S,0,0,1
416,1308,Not Survived,3,"Ware, Mr. Frederick",male,NaN,0,0,359309,8.0500,NaN,S,0,0,1
417,1309,Not Survived,3,"Peter, Master. Michael J",male,NaN,1,1,2668,22.3583,NaN,C,0,0,1