In [1]:
import pandas as pd

In [2]:
# null values find, fill

In [3]:
import numpy as np

In [6]:
df = pd.DataFrame({'Name':['Sourav','Priyanshu','Simran','Anshu',np.nan,'Anurag','Mansi'],'class':['btech','bca','mca','mba',np.nan,'btech','bcom'],'Rollno':[34,np.nan,11,10,np.nan,67,89]})
df

        Name  class  Rollno
0     Sourav  btech    34.0
1  Priyanshu    bca     NaN
2     Simran    mca    11.0
3      Anshu    mba    10.0
4        NaN    NaN     NaN
5     Anurag  btech    67.0
6      Mansi   bcom    89.0

In [7]:
df.isnull()

    Name  class  Rollno
0  False  False   False
1  False  False    True
2  False  False   False
3  False  False   False
4   True   True    True
5  False  False   False
6  False  False   False

In [9]:
df.isnull().sum()

Name      1
class     1
Rollno    2
dtype: int64

In [10]:
df.isnull().any()

Name      True
class     True
Rollno    True
dtype: bool

In [11]:
df.Name

0       Sourav
1    Priyanshu
2       Simran
3        Anshu
4          NaN
5       Anurag
6        Mansi
Name: Name, dtype: str

In [12]:
df[df.Name.isnull()]

  Name class  Rollno
4  NaN   NaN     NaN

In [15]:
df[df.Rollno.isnull()]

        Name class  Rollno
1  Priyanshu   bca     NaN
4        NaN   NaN     NaN

In [16]:
df[df['class'].isnull()]

  Name class  Rollno
4  NaN   NaN     NaN

In [17]:
df['class'].mode()

0    btech
Name: class, dtype: str

In [18]:
df.loc[6,'class']=df['class'].mode()[0]

In [19]:
df

        Name  class  Rollno
0     Sourav  btech    34.0
1  Priyanshu    bca     NaN
2     Simran    mca    11.0
3      Anshu    mba    10.0
4        NaN    NaN     NaN
5     Anurag  btech    67.0
6      Mansi  btech    89.0

In [20]:
df1=pd.DataFrame({'Name':['Sourav','Priyanshu','Simran','Anshu',np.nan,'Anurag','Mansi'],'class':['btech','bca','mca','mba',np.nan,'btech','bcom'],'Rollno':[34,np.nan,11,10,np.nan,67,89]})
df1

        Name  class  Rollno
0     Sourav  btech    34.0
1  Priyanshu    bca     NaN
2     Simran    mca    11.0
3      Anshu    mba    10.0
4        NaN    NaN     NaN
5     Anurag  btech    67.0
6      Mansi   bcom    89.0

In [21]:
df1.fillna(10)

        Name  class  Rollno
0     Sourav  btech    34.0
1  Priyanshu    bca    10.0
2     Simran    mca    11.0
3      Anshu    mba    10.0
4         10     10    10.0
5     Anurag  btech    67.0
6      Mansi   bcom    89.0

In [22]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    6 non-null      str
 1   class   6 non-null      str
 2   Rollno  5 non-null      float64
dtypes: float64(1), str(2)
memory usage: 300.0 bytes

In [23]:
df.describe()

          Rollno
count   5.000000
mean   42.200000
std    34.938517
min    10.000000
25%    11.000000
50%    34.000000
75%    67.000000
max    89.000000

In [24]:
# percentile
l=pd.DataFrame([12,17,14,19,20,21])
l

    0
0  12
1  17
2  14
3  19
4  20
5  21

In [25]:
l.describe()

               0
count   6.000000
mean   17.166667
std     3.544949
min    12.000000
25%    14.750000
50%    18.000000
75%    19.750000
max    21.000000