In [4]:
import pandas as pd

In [21]:
df=pd.DataFrame({'Name':['Mansi','Tania','Pallvi','Seerat'],'Branch':['CSE','BCA','M.com','BCA'],'Age':[22,53,45,25]})
df

     Name Branch  Age
0   Mansi    CSE   22
1   Tania    BCA   53
2  Pallvi  M.com   45
3  Seerat    BCA   25

In [17]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    4 non-null      str
 1   Branch  4 non-null      str
 2   Age     4 non-null      int64
dtypes: int64(1), str(2)
memory usage: 228.0 bytes

In [18]:
df.columns

Index(['Name', 'Branch', 'Age'], dtype='str')

In [19]:
df.describe()

             Age
count   4.000000
mean   36.250000
std    15.129992
min    22.000000
25%    24.250000
50%    35.000000
75%    47.000000
max    53.000000

In [20]:
df[df['Age']>30]

     Name Branch  Age
1   Tania    BCA   53
2  Pallvi  M.com   45

In [23]:
df[df['Branch'] =='BCA']

     Name Branch  Age
1   Tania    BCA   53
3  Seerat    BCA   25

In [33]:
df['Name'].index # to call single column

RangeIndex(start=0, stop=4, step=1)

In [7]:
import numpy as np

In [8]:
df1=pd.DataFrame({'Name':[np.nan,'Tania','Pallvi','Seerat'],'Branch':['CSE',np.nan,'M.com','BCA'],'Age':[22,53,45,25]})
df1

     Name Branch  Age
0     NaN    CSE   22
1   Tania    NaN   53
2  Pallvi  M.com   45
3  Seerat    BCA   25

In [47]:
df1.isnull()

    Name  Branch    Age
0   True   False  False
1  False    True  False
2  False   False  False
3  False   False  False

In [49]:
df1.isnull().sum()

Name      1
Branch    1
Age       0
dtype: int64

In [53]:
df1.Name

0       NaN
1     Tania
2    Pallvi
3    Seerat
Name: Name, dtype: str

In [54]:
df1.Branch

0      CSE
1      NaN
2    M.com
3      BCA
Name: Branch, dtype: str

In [55]:
df1[df1.Name.isnull()]

  Name Branch  Age
0  NaN    CSE   22

In [57]:
df1[df1.Branch.isnull()]

    Name Branch  Age
1  Tania    NaN   53

In [58]:
df1['Age'].mode()

0    22
1    25
2    45
3    53
Name: Age, dtype: int64

In [59]:
df1['Age'].mean()

np.float64(36.25)

In [9]:
df1['Branch'].index

RangeIndex(start=0, stop=4, step=1)

In [10]:
df1.head()

     Name Branch  Age
0     NaN    CSE   22
1   Tania    NaN   53
2  Pallvi  M.com   45
3  Seerat    BCA   25

In [11]:
df1.head(2)

    Name Branch  Age
0    NaN    CSE   22
1  Tania    NaN   53

In [12]:
df1.columns

Index(['Name', 'Branch', 'Age'], dtype='str')

In [14]:
list(df1.Name)

[nan, 'Tania', 'Pallvi', 'Seerat']

In [18]:
df1.columns[:2]

Index(['Name', 'Branch'], dtype='str')

In [20]:
df1[['Name','Age']]

     Name  Age
0     NaN   22
1   Tania   53
2  Pallvi   45
3  Seerat   25

In [28]:
df1['Age'].mean()

np.float64(36.25)

In [32]:
df1.sort_values(by='Age')

     Name Branch  Age
0     NaN    CSE   22
3  Seerat    BCA   25
2  Pallvi  M.com   45
1   Tania    NaN   53

In [33]:
df1.size

12

In [34]:
df1.index

RangeIndex(start=0, stop=4, step=1)

In [35]:
df1.Age.index

RangeIndex(start=0, stop=4, step=1)

In [44]:
df1.loc[:,'Branch']

0      CSE
1      NaN
2    M.com
3      BCA
Name: Branch, dtype: str

In [50]:
df1.iloc[0:2]

    Name Branch  Age
0    NaN    CSE   22
1  Tania    NaN   53

In [51]:
df1.values

array([[nan, 'CSE', 22],
       ['Tania', nan, 53],
       ['Pallvi', 'M.com', 45],
       ['Seerat', 'BCA', 25]], dtype=object)

In [52]:
df1.describe()

             Age
count   4.000000
mean   36.250000
std    15.129992
min    22.000000
25%    24.250000
50%    35.000000
75%    47.000000
max    53.000000

In [57]:
df1['Age'].min()

np.int64(22)

In [60]:
df1['Age'].max()

np.int64(53)

In [61]:
df1.Age.sum()

np.int64(145)

In [64]:
df1.fillna('Mansi').Name

0     Mansi
1     Tania
2    Pallvi
3    Seerat
Name: Name, dtype: str