In [1]:
import pandas as pd

In [2]:
df=pd.read_csv('neet_data.csv')

In [3]:
df

,created_at,retweet_count,source,user_id,user_name,user_description,user_follower_count,user_friends_count,user_location,user_verified,user_url,tweet,length_of_tweet
0,2020-10-31 14:10:28,141,Twitter for Android,1250294694937915394,Rumi,NaN,14,180,NaN,False,NaN,RT @Kwa_Mamkhize: I am giving away R5K to 100 ...,139
1,2020-10-31 14:10:11,1,Twitter for iPhone,57059492,Tom Bewick,"Proud dad of three & cat, @SussexCCC fan. CEO ...",2314,3002,Sussex,False,https://t.co/w6QEi0PBzP,\xf0\x9f\x91\x87This is a really important iss...,140
2,2020-10-31 14:09:48,141,Twitter Web App,1016022678,Lemonade,"Wisdom is knowing the right path to take, Inte...",285,1013,"Bedfordview, South Africa",False,NaN,RT @Kwa_Mamkhize: I am giving away R5K to 100 ...,139
3,2020-10-31 14:09:41,141,Twitter for Android,1085818329816883201,The Rus,NaN,147,467,NaN,False,NaN,RT @Kwa_Mamkhize: I am giving away R5K to 100 ...,139
4,2020-10-31 14:09:22,0,Twitter for Android,1227501071490113537,Sakshi Yadav,it's not my attitude it's my style,2,24,NaN,False,NaN,@RomeshSabharwal @ArvindKejriwal Romesh Sabhar...,140
...,...,...,...,...,...,...,...,...,...,...,...,...,...
47376,2020-10-30 15:29:35,0,Twitter for Android,1168840190426632192,neet_fad_do,Bhola sa chora,254,513,NaN,False,NaN,Friend Request \xe2\x9d\x8c\nAcid request \xe2...,56
47377,2020-10-30 15:29:35,1700,Twitter for Android,1696615807,Yarutai - Garbage NEET,Random person who likes drawing (but not a \nl...,23,754,NaN,False,NaN,RT @Telepeturtle: those are some pretty nice s...,74
47378,2020-10-30 15:28:59,167,Twitter for Android,1313330869113745413,Raushan,NaN,2,2,NaN,False,NaN,"RT @KhushnumaKashm1: (8/n)\n18 year old, Basit...",140
47379,2020-10-30 15:28:37,270,Twitter for Android,1161551282995388416,Vijaykant,Finding the enemies of India \xf0\x9f\x87\xae\...,140,1309,NaN,False,NaN,RT @OpIndia_com: Yogi Adityanath asks chief se...,140
47380,2020-10-30 15:28:14,0,Twitter for Android,1211810532006612992,Icarus,404: \xd8\xaf\xd9\x8a\xd8\xa7\xd9\x86\xd8\xa9 ...,16,45,your friendly local enby,False,NaN,i hate talking to people from my department bu...,139

In [4]:
df.isnull().sum()

created_at                 0
retweet_count              0
source                    19
user_id                    0
user_name                  1
user_description       10871
user_follower_count        0
user_friends_count         0
user_location          21134
user_verified              0
user_url               38101
tweet                      0
length_of_tweet            0
dtype: int64

In [6]:
df[df.source.isnull()]

,created_at,retweet_count,source,user_id,user_name,user_description,user_follower_count,user_friends_count,user_location,user_verified,user_url,tweet,length_of_tweet
7159,2020-10-29 04:11:11,1,NaN,1281299996831150080,Help To Study,Helping Students for scholarships and career g...,216,242,Boston,False,https://t.co/2HNvkWmmXm,RT @ShalomInternat2: Looking to #settle in #ab...,146
11548,2020-10-27 22:42:36,1,NaN,1321204725623230464,Pok\xc3\xa9mon Retweeter,*this account is not affiliated with Nintendo ...,94,0,The Crown Tundra,False,NaN,RT @TonyPajamasBruh: neet! #PokemonSwordShield...,86
11829,2020-10-27 17:32:36,5,NaN,1313328500686815233,Discover-tech,Just a bot helping developers and designers by...,421,0,NaN,False,NaN,RT @PCod3r: Reason #235 why I am a NEET progra...,140
11839,2020-10-27 17:29:21,5,NaN,1317532067987480576,missing_semicolon,Just a bot created to help developers written ...,16,7,NaN,False,NaN,RT @PCod3r: Reason #235 why I am a NEET progra...,140
24180,2020-10-30 06:58:06,4,NaN,1311522988869574657,AI Bot,The definitive AI bot for Industry news,118,253,NaN,False,NaN,RT @goalpatna: Make learning your one true pas...,140
27852,2020-10-29 04:11:11,1,NaN,1281299996831150080,Help To Study,Helping Students for scholarships and career g...,216,242,Boston,False,https://t.co/2HNvkWmmXm,RT @ShalomInternat2: Looking to #settle in #ab...,146
32503,2020-11-08 08:08:46,1,NaN,1294184927433560064,Calzona Bot,Auto RT/Like Callie Torres & Arizona Robbins r...,61,0,NaN,False,NaN,RT @rascalaf: I neet to be Callie Torres,40
33016,2020-11-08 03:37:00,1,NaN,1295715136141963267,Education World,All education content. Education changes the l...,453,5,NaN,False,NaN,RT @ca_tamizh: I will tweet #BanNEET daily unt...,140
34115,2020-11-07 07:59:26,1,NaN,1295715136141963267,Education World,All education content. Education changes the l...,453,5,NaN,False,NaN,RT @CHAUHANishu1: #UPSEE\nOffline/Online Class...,139
34312,2020-11-07 05:04:51,1,NaN,1295715136141963267,Education World,All education content. Education changes the l...,453,5,NaN,False,NaN,RT @Ifluxeducare: Our Toppers\n\xf0\x9f\x91\x8...,140
34329,2020-11-07 04:47:17,1,NaN,1295715136141963267,Education World,All education content. Education changes the l...,453,5,NaN,False,NaN,RT @neerajnirwals: NEET Counselling 2020 provi...,140
34441,2020-11-07 03:14:42,1,NaN,1295715136141963267,Education World,All education content. Education changes the l...,453,5,NaN,False,NaN,RT @ca_tamizh: I will tweet #BanNEET daily unt...,140
35478,2020-11-06 10:16:10,1,NaN,1295715136141963267,Education World,All education content. Education changes the l...,453,5,NaN,False,NaN,RT @indiacom: NEET State Counselling 2020: Dat...,140
36074,2020-11-06 02:36:59,1,NaN,1295715136141963267,Education World,All education content. Education changes the l...,453,5,NaN,False,NaN,RT @ca_tamizh: I will tweet #BanNEET daily unt...,140
36313,2020-11-05 20:45:00,2,NaN,1321204725623230464,Pok\xc3\xa9mon Retweeter,*this account is not affiliated with Nintendo ...,218,0,The Crown Tundra,False,NaN,"RT @Joemommateehee: I have bunneary, but neet ...",128
42722,2020-11-02 05:39:13,1,NaN,1295715136141963267,Education World,All education content. Education changes the l...,453,5,NaN,False,NaN,RT @medicosis: Can you answer today\xe2\x80\x9...,140
43449,2020-11-02 02:15:25,1,NaN,1295715136141963267,Education World,All education content. Education changes the l...,453,5,NaN,False,NaN,RT @Killer_Mehta: Who said money can't buy hap...,117
43497,2020-11-02 02:01:11,138,NaN,1319204739523854337,India Bot,Spreading India amazing trending tweets \xf0\x...,14,0,India,False,NaN,RT @TrendsDmk: Tamil Nadu &amp; Tamil People a...,144
45063,2020-11-01 01:00:02,0,NaN,1286845213978300416,Reginald,Markov chain bot. Generator of sentences. The ...,26,0,NaN,False,NaN,the neet doesn't even want to be a virgin anym...,56

In [9]:
df[df.loc[:,'source'] == 'Twitter for Android']

,created_at,retweet_count,source,user_id,user_name,user_description,user_follower_count,user_friends_count,user_location,user_verified,user_url,tweet,length_of_tweet
0,2020-10-31 14:10:28,141,Twitter for Android,1250294694937915394,Rumi,NaN,14,180,NaN,False,NaN,RT @Kwa_Mamkhize: I am giving away R5K to 100 ...,139
3,2020-10-31 14:09:41,141,Twitter for Android,1085818329816883201,The Rus,NaN,147,467,NaN,False,NaN,RT @Kwa_Mamkhize: I am giving away R5K to 100 ...,139
4,2020-10-31 14:09:22,0,Twitter for Android,1227501071490113537,Sakshi Yadav,it's not my attitude it's my style,2,24,NaN,False,NaN,@RomeshSabharwal @ArvindKejriwal Romesh Sabhar...,140
5,2020-10-31 14:07:29,80,Twitter for Android,1160942418,nabat kapoor,Retired. RTs not endorsements.,838,29,kolkatta active 2014,False,NaN,RT @DrSubhasree: Congratulations #Delhi for sc...,140
6,2020-10-31 14:06:34,141,Twitter for Android,1307041172444119056,Stanleyholmes9,I love rapping and I am dam good at it...,14,146,"Durban, South Africa",False,NaN,RT @Kwa_Mamkhize: I am giving away R5K to 100 ...,139
...,...,...,...,...,...,...,...,...,...,...,...,...,...
47376,2020-10-30 15:29:35,0,Twitter for Android,1168840190426632192,neet_fad_do,Bhola sa chora,254,513,NaN,False,NaN,Friend Request \xe2\x9d\x8c\nAcid request \xe2...,56
47377,2020-10-30 15:29:35,1700,Twitter for Android,1696615807,Yarutai - Garbage NEET,Random person who likes drawing (but not a \nl...,23,754,NaN,False,NaN,RT @Telepeturtle: those are some pretty nice s...,74
47378,2020-10-30 15:28:59,167,Twitter for Android,1313330869113745413,Raushan,NaN,2,2,NaN,False,NaN,"RT @KhushnumaKashm1: (8/n)\n18 year old, Basit...",140
47379,2020-10-30 15:28:37,270,Twitter for Android,1161551282995388416,Vijaykant,Finding the enemies of India \xf0\x9f\x87\xae\...,140,1309,NaN,False,NaN,RT @OpIndia_com: Yogi Adityanath asks chief se...,140
47380,2020-10-30 15:28:14,0,Twitter for Android,1211810532006612992,Icarus,404: \xd8\xaf\xd9\x8a\xd8\xa7\xd9\x86\xd8\xa9 ...,16,45,your friendly local enby,False,NaN,i hate talking to people from my department bu...,139

In [10]:
df[df.loc[:,'retweet_count'] == 141]

,created_at,retweet_count,source,user_id,user_name,user_description,user_follower_count,user_friends_count,user_location,user_verified,user_url,tweet,length_of_tweet
0,2020-10-31 14:10:28,141,Twitter for Android,1250294694937915394,Rumi,NaN,14,180,NaN,False,NaN,RT @Kwa_Mamkhize: I am giving away R5K to 100 ...,139
2,2020-10-31 14:09:48,141,Twitter Web App,1016022678,Lemonade,"Wisdom is knowing the right path to take, Inte...",285,1013,"Bedfordview, South Africa",False,NaN,RT @Kwa_Mamkhize: I am giving away R5K to 100 ...,139
3,2020-10-31 14:09:41,141,Twitter for Android,1085818329816883201,The Rus,NaN,147,467,NaN,False,NaN,RT @Kwa_Mamkhize: I am giving away R5K to 100 ...,139
6,2020-10-31 14:06:34,141,Twitter for Android,1307041172444119056,Stanleyholmes9,I love rapping and I am dam good at it...,14,146,"Durban, South Africa",False,NaN,RT @Kwa_Mamkhize: I am giving away R5K to 100 ...,139
8,2020-10-31 14:06:06,141,Twitter for Android,789577875380924416,The Immigrant \xf0\x9f\x87\xbf\xf0\x9f\x87\xbc...,\xc2\xb0 My tweets are my views. \n\xc2\xb0Pat...,1161,1271,Africa,False,NaN,RT @Kwa_Mamkhize: I am giving away R5K to 100 ...,139
...,...,...,...,...,...,...,...,...,...,...,...,...,...
32914,2020-11-08 05:11:38,141,Twitter for Android,1719068636,\xe0\xa4\xac\xe0\xa5\x87\xe0\xa4\xb0\xe0\xa5\x...,student,50,257,India,False,NaN,RT @ShwetaPatwa1: If u can conduct JEE_NEET_ f...,144
32915,2020-11-08 05:11:26,141,Twitter for Android,1257887829256032256,Durgesh Yadav(Rishu)\xf0\x9f\x93\x92\xf0\x9f\x...,"D.el.ed (BTC) 2017-2019\nTET,CTET Qualified \x...",315,344,"Sultanpur, India",False,https://t.co/xl02hzRtBN,RT @ShwetaPatwa1: If u can conduct JEE_NEET_ f...,144
32917,2020-11-08 05:10:36,141,Twitter for Android,1258139792832901122,Shweta Patwa,d.el.ed2017-19,2539,1404,"UP, India",False,NaN,If u can conduct JEE_NEET_ final yr exam &amp...,144
39554,2020-11-04 02:31:36,141,Twitter Web App,1051653736659996673,Canton_\xd0\xb3\xd0\xbe\xcc\x81\xd0\xbf\xd0\xb...,\xe8\x87\xaa\xe5\xae\x85\xe8\xad\xa6\xe5\xa4\x...,512,2171,"\xe5\xb9\xbf\xe4\xb8\x9c, \xe4\xb8\xad\xe5\x8d...",False,NaN,RT @capcomkai: Right scale for you? The autobo...,90
40871,2020-11-03 04:20:55,141,Twitter for iPhone,2259539461,jen,NaN,26,29,in your area,False,NaN,RT @partydogge: what is this thing? i keep see...,83

In [18]:
df.loc[df['retweet_count'] == df['retweet_count'].max(),['user_follower_count','user_friends_count']]

       user_follower_count  user_friends_count
32860                   62                 115

In [23]:
df.loc[df['user_follower_count'] == df['user_follower_count'].max(),['user_name','source']]

      user_name                          source
44355      NDTV  Twitter Media Studio - LiveCut
44367      NDTV  Twitter Media Studio - LiveCut
44424      NDTV  Twitter Media Studio - LiveCut
44436      NDTV  Twitter Media Studio - LiveCut

In [24]:
df['user_follower_count'].max()

np.int64(13934355)

In [26]:
df['retweet_count'].max()

np.int64(614304)

In [28]:
df.tail(50)

,created_at,retweet_count,source,user_id,user_name,user_description,user_follower_count,user_friends_count,user_location,user_verified,user_url,tweet,length_of_tweet
47331,2020-10-30 15:54:27,47,Twitter for Android,39060841,Contractor Kuruvi,Dravidian,474,1160,NaN,False,NaN,RT @Hereprak: 13 students killed themselves fo...,140
47332,2020-10-30 15:53:51,0,Twitter for Android,1146318087475437568,\xe2\x9d\x84\xef\xb8\x8f CEO of kaiba propagan...,\xef\xbe\x9f\xef\xbd\xa1\xef\xbd\xa5*.\xef\xbe...,523,370,\xe2\x98\x85 28 \xe2\x80\xa2 ca \xe2\x86\x92 a...,False,https://t.co/FnPOaifML8,@AlishizueQ LOL what's a NEET??,31
47333,2020-10-30 15:53:11,1,Twitter for Android,1026239606491107328,ajae,spl2 fa / wannabe designer,24,26,by myself,False,https://t.co/fD5jZK1fuH,RT @YonoSSB: @Neet_O_ @NairoMK Lol notice how ...,140
47334,2020-10-30 15:53:05,0,Twitter for Android,1026239606491107328,ajae,spl2 fa / wannabe designer,24,26,by myself,False,https://t.co/fD5jZK1fuH,@YonoSSB @Neet_O_ @NairoMK This is my literal ...,125
47335,2020-10-30 15:53:04,1,Twitter for Android,789476510235291648,NEET's gatcha acc \xc2\xb0\xe2\x80\xa2\xc2\xb0...,neet's vibing account || gacha hell ( genshini...,15,10,NaN,False,NaN,RT @NEET_himee: Uhh... how do I explain this o...,75
47336,2020-10-30 15:52:53,0,Twitter for Android,789476510235291648,NEET's gatcha acc \xc2\xb0\xe2\x80\xa2\xc2\xb0...,neet's vibing account || gacha hell ( genshini...,15,10,NaN,False,NaN,Thats not ayerscape but I'll take her too http...,89
47337,2020-10-30 15:52:18,0,Twitter Web App,1316184087669792768,Ali Shizue The Witch of Despair\xe2\x9b\xa7,She/Her trans and Smug anime girl\nMTG/Overwat...,84,153,NaN,False,NaN,@fueledbykaiba Im glad youre not a gross Yugio...,74
47338,2020-10-30 15:51:44,0,Twitter for iPhone,3249255046,Big Pun!,Baltimore \xe2\x9c\x88\xef\xb8\x8f NY \xe2\x9c...,803,374,NaN,False,NaN,Who got hbo max? Im trynna watch Meek Mill new...,54
47339,2020-10-30 15:50:05,0,Twitter for iPhone,1089602809803096064,Legend \xe2\x80\x9cBubble\xe2\x80\x9d,bubs/bubbie. pizza slut. i love fat cats and f...,2283,166,NaN,False,https://t.co/q8kdNH5goK,@sweaty_neet @okuudere those shorts are gonna ...,66
47340,2020-10-30 15:49:57,0,Twitter for Android,789476510235291648,NEET's gatcha acc \xc2\xb0\xe2\x80\xa2\xc2\xb0...,neet's vibing account || gacha hell ( genshini...,15,10,NaN,False,NaN,Please zhongli come home i beg of you,37
47341,2020-10-30 15:49:39,3339,Twitter for Android,1317797255189983232,Kunal,NaN,0,1,NaN,False,NaN,RT @Kailash46280213: Aaj NDTV india par teache...,140
47342,2020-10-30 15:49:23,4913,Twitter for Android,789476510235291648,NEET's gatcha acc \xc2\xb0\xe2\x80\xa2\xc2\xb0...,neet's vibing account || gacha hell ( genshini...,15,10,NaN,False,NaN,RT @paipitations: mondstadt day off \xf0\x9f\x...,81
47343,2020-10-30 15:49:16,0,Twitter for iPhone,864977383694241794,rocky \xf0\x9f\x8e\x8f CEO of karamatsu,| she/her | 17 | \xf0\x9f\x92\x99 i\xe2\x80\x9...,104,38,NaN,False,NaN,the ososan pr team should\xe2\x80\x99ve said T...,47
47344,2020-10-30 15:48:54,0,Twitter for Android,287435785,Otrebmuh,343i is shit.\nDaedragender\xf0\x9f\x93\x96\xf...,37,481,NaN,False,NaN,"@0xCAFEBEEF No you don't, being a NEET sucks, ...",87
47345,2020-10-30 15:48:47,6338,Twitter for iPhone,911336300002680832,janet \xf0\x9f\x8c\xa7 PARTYING,#PHIL: k | she/her | 15 | page 209 belongs to ...,610,1053,BLM \xe2\x99\xa1 ACAB,False,NaN,RT @AmazingPhil: Someone is moving into our ap...,130
47346,2020-10-30 15:48:45,0,Twitter for Android,721559348,treacherous deathcat,eilene \xf0\x9f\x94\xaa evil catgirl \xf0\x9f...,3037,1065,yuria molkot @ leviathan,False,https://t.co/i36bJN2YMJ,@sweaty_neet this is extremely true,35
47347,2020-10-30 15:48:45,0,WordPress.com,1259781444185944066,Amazon India Offers,Daily Deal Offers. Follow us to get more Savin...,91,236,NaN,False,https://t.co/NxIJNz4jQH,Objective NCERT Gear Up Biology for NEET 2021 ...,69
47348,2020-10-30 15:48:43,0,WordPress.com,376197627,Manish Salunke,Web Developer,474,1363,"Pune, India",False,NaN,Objective NCERT Gear Up Biology for NEET 2021 ...,69
47349,2020-10-30 15:48:42,0,WordPress.com,1260150415146070016,Swati Sharma \xe2\xad\x90\xe2\xad\x90\xe2\xad\...,\xf0\x9f\x87\xae\xf0\x9f\x87\xb3 INDIAN \xf0\x...,238,485,NaN,False,https://t.co/2HgX7svAne,Objective NCERT Gear Up Biology for NEET 2021 ...,69
47350,2020-10-30 15:48:20,324,Twitter for Android,789476510235291648,NEET's gatcha acc \xc2\xb0\xe2\x80\xa2\xc2\xb0...,neet's vibing account || gacha hell ( genshini...,15,10,NaN,False,NaN,RT @flowermagus: zhongli highlights from the s...,77
47351,2020-10-30 15:46:53,0,Twitter Web App,1222115365880074240,Deepanjali,Speak don't shout,92,23,NaN,False,NaN,@saksham65694969 @CACSCMARajat Neet had isolat...,98
47352,2020-10-30 15:45:52,37,Twitter for Android,127826034,Shalika Malviya,#FamilyMedicine Specialist.\nHealth literacy a...,356,896,T.N./U.P. India,False,NaN,RT @drsitu: Is it ethical to force successful ...,140
47353,2020-10-30 15:45:01,3,Twitter for Android,1299979335084900352,\xe0\xa4\xac\xe0\xa5\x87\xe0\xa4\xb0\xe0\xa5\x...,NaN,7,38,NaN,False,NaN,RT @ntb582: \xf0\x9f\x8f\x85 Congratulations \...,140
47354,2020-10-30 15:44:14,0,Twitter Web App,1219016292759302144,@laphroaigautist\xf0\x9f\x80\x84\xef\xb8\x8f\x...,master race baiter,317,1428,United States,False,https://t.co/Js0ip4wpJ9,@cringepoland the respect i get as a neet is s...,70
47355,2020-10-30 15:43:57,0,Twitter for Android,1278598013707890689,saksham sood,#GST Consultant#ICAI#Verge of becoming CA # A ...,6,34,NaN,False,NaN,@Deepanj28952839 @CACSCMARajat No paise power....,140
47356,2020-10-30 15:43:13,0,feather for iOS,768080227331256320,\xe3\x81\xaf\xe3\x81\xaa\xe3\x81\x9f\xe3\x81\x8b,\xef\xbc\x91\xe3\x83\xb6\xe6\x9c\x88\xe9\xa3\x...,141,378,\xf0\x9f\x8c\xb7\xf0\x9f\x8c\xb9\xf0\x9f\x8c\x...,False,https://t.co/JkQcBGfg2W,#nowplaying RUN AWAYS by m-flo loves chelmico ...,69
47357,2020-10-30 15:42:39,0,Twitter for Android,856296749195026432,Aurangzeb,NaN,85,348,tombouctou,False,NaN,@Indian_Foreverr @dhaivat_chhaya @SalmanNizami...,140
47358,2020-10-30 15:38:45,0,Twitter for Android,721559348,treacherous deathcat,eilene \xf0\x9f\x94\xaa evil catgirl \xf0\x9f...,3037,1065,yuria molkot @ leviathan,False,https://t.co/i36bJN2YMJ,@sweaty_neet people should buy it for me as re...,81
47359,2020-10-30 15:38:30,0,Twitter for iPhone,283556478,NewsFirst,XnewsFirst News & information to the Tamil vie...,114,243,"Dindigul, India",False,https://t.co/RUZB00OK8P,"After govt takes executive route, Tamil Nadu g...",133
47360,2020-10-30 15:37:48,4,Twitter for Android,1137569818150752259,WARD-35 Perambur-Chennai,Social Service | Public Opinion & Forum | Meet...,13,30,NaN,False,NaN,RT @GovindarajPM: A Big day for Govt school st...,139
47361,2020-10-30 15:36:59,0,Twitter for Android,1263928531102265345,\xe3\x83\x9f\xe3\x82\xb9\xe3\x81\x9f\xe3\x82\x93,\xe3\x82\xb5\xe3\x82\xb9\xe3\x83\x9a\xe3\x83\x...,294,346,\xe3\x83\x8d\xe3\x82\xac\xe3\x83\x86\xe3\x82\x...,False,NaN,trick or neet,13
47362,2020-10-30 15:36:43,0,Twitter Web App,1207808797,rumi,\xe7\xa7\x98\xe5\xb0\x81\xe5\x80\xb6\xe6\xa5\x...,141,953,melbourne \xef\xbd\x9c touhou \xef\xbd\x9c cs/...,False,https://t.co/ZPOqYcvgmW,really really really want to go back to being ...,73
47363,2020-10-30 15:36:43,0,"Cheap Bots, Done Quick!",778305113316143104,LNTitles,NaN,33,0,NaN,False,NaN,My quiet childhood friend can't be a NEET!,42
47364,2020-10-30 15:35:53,4,Twitter for Android,915556193048846336,@NrthChennaiMP_2B,NaN,91,33,Chennai,False,NaN,RT @GovindarajPM: A Big day for Govt school st...,139
47365,2020-10-30 15:35:08,0,Twitter for Android,1096516185020030976,Mariselvamohan,"cricket, politics",14,79,NaN,False,NaN,https://t.co/dEQkZ1RvWI\n@Ondippulee @Pandidur...,139
47366,2020-10-30 15:35:06,11,Twitter Web App,1445165456,Coco & Cookie (It's a HER ),I am coco to my coffee \xf0\x9f\x91\xa9\xe2\x8...,35,29,NaN,False,NaN,"Let me tell something honestly, my neighbour a...",139
47367,2020-10-30 15:35:00,0,Twitter for Android,1098400796901892097,TheAngryGamer360,"19, He/Him, Gaming Youtuber, Console Pleb, Asp...",134,190,"Michigan, USA",False,https://t.co/lHPQe2KbOk,@0xCAFEBEEF Wanna trade? You can be MY neet,43
47368,2020-10-30 15:34:41,0,Twitter Web App,865381253293326336,gray...\xf0\x9f\x8e\xa3\xf0\x9f\x92\x99\xf0\x9...,Gray/Pish\xf0\x9f\x90\xb6 | 17 | \xf0\x9f\x87\...,456,523,NaN,False,https://t.co/YApBscVuzy,are you neet..... are you neet.... my favorite...,96
47369,2020-10-30 15:33:58,0,Twitter for Android,721559348,treacherous deathcat,eilene \xf0\x9f\x94\xaa evil catgirl \xf0\x9f...,3037,1065,yuria molkot @ leviathan,False,https://t.co/i36bJN2YMJ,@sweaty_neet it's good...,25
47370,2020-10-30 15:33:44,0,Twitter for Android,47350066,God Knows Best,NaN,0,4971,NaN,False,NaN,Banwarilal Purohit: Tamil Nadu governor gives ...,136
47371,2020-10-30 15:33:21,0,Twitter for Android,1093482865,120lbs of lean cafebeef,"cafebeef - if you think i'm cute, you're gay. ...",10325,159,"London, England",False,https://t.co/sxZD6jpOst,i miss being a neet,19
47372,2020-10-30 15:33:01,0,Twitter Web App,2877387148,\xe3\x80\x90 \xe2\x99\xa1 \xe3\x80\x91\xe3\x80...,[\xe2\x98\x86] [ lily ] I { cis she/her } I\xe...,782,1246,nowhere near you,False,https://t.co/C2wMcAe09Q,@epistellar im just a simple neet...,36
47373,2020-10-30 15:31:03,3,agaramuthala,1270275832968175616,\xe0\xae\x85\xe0\xae\x95\xe0\xae\xb0\xe0\xae\x...,#\xe0\xae\x89\xe0\xae\xb2\xe0\xae\x95\xe0\xae\...,172,107,Tamil Nadu,False,https://t.co/JW3vypGg4e,RT @ieeducation_job: #TamilNadu governor clear...,135
47374,2020-10-30 15:31:03,1,agaramuthala,1270275832968175616,\xe0\xae\x85\xe0\xae\x95\xe0\xae\xb0\xe0\xae\x...,#\xe0\xae\x89\xe0\xae\xb2\xe0\xae\x95\xe0\xae\...,172,107,Tamil Nadu,False,https://t.co/JW3vypGg4e,RT @KanoonSangrah: Tamil Nadu Governor passes ...,140
47375,2020-10-30 15:30:28,1,Twitter for Android,1229737514283307008,Kanoon Sangrah,Connecting people with Kanoon!!,69,109,Delhi,False,https://t.co/1vUSuj068K,Tamil Nadu Governor passes order to provide 7....,132
47376,2020-10-30 15:29:35,0,Twitter for Android,1168840190426632192,neet_fad_do,Bhola sa chora,254,513,NaN,False,NaN,Friend Request \xe2\x9d\x8c\nAcid request \xe2...,56
47377,2020-10-30 15:29:35,1700,Twitter for Android,1696615807,Yarutai - Garbage NEET,Random person who likes drawing (but not a \nl...,23,754,NaN,False,NaN,RT @Telepeturtle: those are some pretty nice s...,74
47378,2020-10-30 15:28:59,167,Twitter for Android,1313330869113745413,Raushan,NaN,2,2,NaN,False,NaN,"RT @KhushnumaKashm1: (8/n)\n18 year old, Basit...",140
47379,2020-10-30 15:28:37,270,Twitter for Android,1161551282995388416,Vijaykant,Finding the enemies of India \xf0\x9f\x87\xae\...,140,1309,NaN,False,NaN,RT @OpIndia_com: Yogi Adityanath asks chief se...,140
47380,2020-10-30 15:28:14,0,Twitter for Android,1211810532006612992,Icarus,404: \xd8\xaf\xd9\x8a\xd8\xa7\xd9\x86\xd8\xa9 ...,16,45,your friendly local enby,False,NaN,i hate talking to people from my department bu...,139

In [29]:
df.tail()

,created_at,retweet_count,source,user_id,user_name,user_description,user_follower_count,user_friends_count,user_location,user_verified,user_url,tweet,length_of_tweet
47376,2020-10-30 15:29:35,0,Twitter for Android,1168840190426632192,neet_fad_do,Bhola sa chora,254,513,NaN,False,NaN,Friend Request \xe2\x9d\x8c\nAcid request \xe2...,56
47377,2020-10-30 15:29:35,1700,Twitter for Android,1696615807,Yarutai - Garbage NEET,Random person who likes drawing (but not a \nl...,23,754,NaN,False,NaN,RT @Telepeturtle: those are some pretty nice s...,74
47378,2020-10-30 15:28:59,167,Twitter for Android,1313330869113745413,Raushan,NaN,2,2,NaN,False,NaN,"RT @KhushnumaKashm1: (8/n)\n18 year old, Basit...",140
47379,2020-10-30 15:28:37,270,Twitter for Android,1161551282995388416,Vijaykant,Finding the enemies of India \xf0\x9f\x87\xae\...,140,1309,NaN,False,NaN,RT @OpIndia_com: Yogi Adityanath asks chief se...,140
47380,2020-10-30 15:28:14,0,Twitter for Android,1211810532006612992,Icarus,404: \xd8\xaf\xd9\x8a\xd8\xa7\xd9\x86\xd8\xa9 ...,16,45,your friendly local enby,False,NaN,i hate talking to people from my department bu...,139

In [30]:
df.head()

,created_at,retweet_count,source,user_id,user_name,user_description,user_follower_count,user_friends_count,user_location,user_verified,user_url,tweet,length_of_tweet
0,2020-10-31 14:10:28,141,Twitter for Android,1250294694937915394,Rumi,NaN,14,180,NaN,False,NaN,RT @Kwa_Mamkhize: I am giving away R5K to 100 ...,139
1,2020-10-31 14:10:11,1,Twitter for iPhone,57059492,Tom Bewick,"Proud dad of three & cat, @SussexCCC fan. CEO ...",2314,3002,Sussex,False,https://t.co/w6QEi0PBzP,\xf0\x9f\x91\x87This is a really important iss...,140
2,2020-10-31 14:09:48,141,Twitter Web App,1016022678,Lemonade,"Wisdom is knowing the right path to take, Inte...",285,1013,"Bedfordview, South Africa",False,NaN,RT @Kwa_Mamkhize: I am giving away R5K to 100 ...,139
3,2020-10-31 14:09:41,141,Twitter for Android,1085818329816883201,The Rus,NaN,147,467,NaN,False,NaN,RT @Kwa_Mamkhize: I am giving away R5K to 100 ...,139
4,2020-10-31 14:09:22,0,Twitter for Android,1227501071490113537,Sakshi Yadav,it's not my attitude it's my style,2,24,NaN,False,NaN,@RomeshSabharwal @ArvindKejriwal Romesh Sabhar...,140

In [4]:
df.isnull().sum()

created_at                 0
retweet_count              0
source                    19
user_id                    0
user_name                  1
user_description       10871
user_follower_count        0
user_friends_count         0
user_location          21134
user_verified              0
user_url               38101
tweet                      0
length_of_tweet            0
dtype: int64

In [7]:
df.drop('user_url',axis=1,inplace=True)

In [8]:
df.isnull().sum()

created_at                 0
retweet_count              0
source                    19
user_id                    0
user_name                  1
user_description       10871
user_follower_count        0
user_friends_count         0
user_location          21134
user_verified              0
tweet                      0
length_of_tweet            0
dtype: int64

In [9]:
df.drop('user_location',axis=1,inplace=True)

In [10]:
df

,created_at,retweet_count,source,user_id,user_name,user_description,user_follower_count,user_friends_count,user_verified,tweet,length_of_tweet
0,2020-10-31 14:10:28,141,Twitter for Android,1250294694937915394,Rumi,NaN,14,180,False,RT @Kwa_Mamkhize: I am giving away R5K to 100 ...,139
1,2020-10-31 14:10:11,1,Twitter for iPhone,57059492,Tom Bewick,"Proud dad of three & cat, @SussexCCC fan. CEO ...",2314,3002,False,\xf0\x9f\x91\x87This is a really important iss...,140
2,2020-10-31 14:09:48,141,Twitter Web App,1016022678,Lemonade,"Wisdom is knowing the right path to take, Inte...",285,1013,False,RT @Kwa_Mamkhize: I am giving away R5K to 100 ...,139
3,2020-10-31 14:09:41,141,Twitter for Android,1085818329816883201,The Rus,NaN,147,467,False,RT @Kwa_Mamkhize: I am giving away R5K to 100 ...,139
4,2020-10-31 14:09:22,0,Twitter for Android,1227501071490113537,Sakshi Yadav,it's not my attitude it's my style,2,24,False,@RomeshSabharwal @ArvindKejriwal Romesh Sabhar...,140
...,...,...,...,...,...,...,...,...,...,...,...
47376,2020-10-30 15:29:35,0,Twitter for Android,1168840190426632192,neet_fad_do,Bhola sa chora,254,513,False,Friend Request \xe2\x9d\x8c\nAcid request \xe2...,56
47377,2020-10-30 15:29:35,1700,Twitter for Android,1696615807,Yarutai - Garbage NEET,Random person who likes drawing (but not a \nl...,23,754,False,RT @Telepeturtle: those are some pretty nice s...,74
47378,2020-10-30 15:28:59,167,Twitter for Android,1313330869113745413,Raushan,NaN,2,2,False,"RT @KhushnumaKashm1: (8/n)\n18 year old, Basit...",140
47379,2020-10-30 15:28:37,270,Twitter for Android,1161551282995388416,Vijaykant,Finding the enemies of India \xf0\x9f\x87\xae\...,140,1309,False,RT @OpIndia_com: Yogi Adityanath asks chief se...,140
47380,2020-10-30 15:28:14,0,Twitter for Android,1211810532006612992,Icarus,404: \xd8\xaf\xd9\x8a\xd8\xa7\xd9\x86\xd8\xa9 ...,16,45,False,i hate talking to people from my department bu...,139

In [11]:
df.isnull().sum()

created_at                 0
retweet_count              0
source                    19
user_id                    0
user_name                  1
user_description       10871
user_follower_count        0
user_friends_count         0
user_verified              0
tweet                      0
length_of_tweet            0
dtype: int64

In [12]:
df.drop('user_description',axis=1,inplace=True)

In [13]:
df.isnull().sum()

created_at              0
retweet_count           0
source                 19
user_id                 0
user_name               1
user_follower_count     0
user_friends_count      0
user_verified           0
tweet                   0
length_of_tweet         0
dtype: int64

In [15]:
df[df.source.isnull()]

,created_at,retweet_count,source,user_id,user_name,user_follower_count,user_friends_count,user_verified,tweet,length_of_tweet
7159,2020-10-29 04:11:11,1,NaN,1281299996831150080,Help To Study,216,242,False,RT @ShalomInternat2: Looking to #settle in #ab...,146
11548,2020-10-27 22:42:36,1,NaN,1321204725623230464,Pok\xc3\xa9mon Retweeter,94,0,False,RT @TonyPajamasBruh: neet! #PokemonSwordShield...,86
11829,2020-10-27 17:32:36,5,NaN,1313328500686815233,Discover-tech,421,0,False,RT @PCod3r: Reason #235 why I am a NEET progra...,140
11839,2020-10-27 17:29:21,5,NaN,1317532067987480576,missing_semicolon,16,7,False,RT @PCod3r: Reason #235 why I am a NEET progra...,140
24180,2020-10-30 06:58:06,4,NaN,1311522988869574657,AI Bot,118,253,False,RT @goalpatna: Make learning your one true pas...,140
27852,2020-10-29 04:11:11,1,NaN,1281299996831150080,Help To Study,216,242,False,RT @ShalomInternat2: Looking to #settle in #ab...,146
32503,2020-11-08 08:08:46,1,NaN,1294184927433560064,Calzona Bot,61,0,False,RT @rascalaf: I neet to be Callie Torres,40
33016,2020-11-08 03:37:00,1,NaN,1295715136141963267,Education World,453,5,False,RT @ca_tamizh: I will tweet #BanNEET daily unt...,140
34115,2020-11-07 07:59:26,1,NaN,1295715136141963267,Education World,453,5,False,RT @CHAUHANishu1: #UPSEE\nOffline/Online Class...,139
34312,2020-11-07 05:04:51,1,NaN,1295715136141963267,Education World,453,5,False,RT @Ifluxeducare: Our Toppers\n\xf0\x9f\x91\x8...,140
34329,2020-11-07 04:47:17,1,NaN,1295715136141963267,Education World,453,5,False,RT @neerajnirwals: NEET Counselling 2020 provi...,140
34441,2020-11-07 03:14:42,1,NaN,1295715136141963267,Education World,453,5,False,RT @ca_tamizh: I will tweet #BanNEET daily unt...,140
35478,2020-11-06 10:16:10,1,NaN,1295715136141963267,Education World,453,5,False,RT @indiacom: NEET State Counselling 2020: Dat...,140
36074,2020-11-06 02:36:59,1,NaN,1295715136141963267,Education World,453,5,False,RT @ca_tamizh: I will tweet #BanNEET daily unt...,140
36313,2020-11-05 20:45:00,2,NaN,1321204725623230464,Pok\xc3\xa9mon Retweeter,218,0,False,"RT @Joemommateehee: I have bunneary, but neet ...",128
42722,2020-11-02 05:39:13,1,NaN,1295715136141963267,Education World,453,5,False,RT @medicosis: Can you answer today\xe2\x80\x9...,140
43449,2020-11-02 02:15:25,1,NaN,1295715136141963267,Education World,453,5,False,RT @Killer_Mehta: Who said money can't buy hap...,117
43497,2020-11-02 02:01:11,138,NaN,1319204739523854337,India Bot,14,0,False,RT @TrendsDmk: Tamil Nadu &amp; Tamil People a...,144
45063,2020-11-01 01:00:02,0,NaN,1286845213978300416,Reginald,26,0,False,the neet doesn't even want to be a virgin anym...,56

In [21]:
df["source"] = df["source"].fillna("Unknown")

In [23]:
df['source']

0        Twitter for Android
1         Twitter for iPhone
2            Twitter Web App
3        Twitter for Android
4        Twitter for Android
                ...
47376    Twitter for Android
47377    Twitter for Android
47378    Twitter for Android
47379    Twitter for Android
47380    Twitter for Android
Name: source, Length: 47381, dtype: str

In [26]:
df['source'].isnull().sum()

np.int64(0)

In [30]:
df.insert(3,'is_allow','True')

In [31]:
df

,created_at,retweet_count,source,is_allow,user_id,user_name,user_follower_count,user_friends_count,user_verified,tweet,length_of_tweet
0,2020-10-31 14:10:28,141,Twitter for Android,True,1250294694937915394,Rumi,14,180,False,RT @Kwa_Mamkhize: I am giving away R5K to 100 ...,139
1,2020-10-31 14:10:11,1,Twitter for iPhone,True,57059492,Tom Bewick,2314,3002,False,\xf0\x9f\x91\x87This is a really important iss...,140
2,2020-10-31 14:09:48,141,Twitter Web App,True,1016022678,Lemonade,285,1013,False,RT @Kwa_Mamkhize: I am giving away R5K to 100 ...,139
3,2020-10-31 14:09:41,141,Twitter for Android,True,1085818329816883201,The Rus,147,467,False,RT @Kwa_Mamkhize: I am giving away R5K to 100 ...,139
4,2020-10-31 14:09:22,0,Twitter for Android,True,1227501071490113537,Sakshi Yadav,2,24,False,@RomeshSabharwal @ArvindKejriwal Romesh Sabhar...,140
...,...,...,...,...,...,...,...,...,...,...,...
47376,2020-10-30 15:29:35,0,Twitter for Android,True,1168840190426632192,neet_fad_do,254,513,False,Friend Request \xe2\x9d\x8c\nAcid request \xe2...,56
47377,2020-10-30 15:29:35,1700,Twitter for Android,True,1696615807,Yarutai - Garbage NEET,23,754,False,RT @Telepeturtle: those are some pretty nice s...,74
47378,2020-10-30 15:28:59,167,Twitter for Android,True,1313330869113745413,Raushan,2,2,False,"RT @KhushnumaKashm1: (8/n)\n18 year old, Basit...",140
47379,2020-10-30 15:28:37,270,Twitter for Android,True,1161551282995388416,Vijaykant,140,1309,False,RT @OpIndia_com: Yogi Adityanath asks chief se...,140
47380,2020-10-30 15:28:14,0,Twitter for Android,True,1211810532006612992,Icarus,16,45,False,i hate talking to people from my department bu...,139

In [33]:
df.drop('tweet',axis=1,inplace=True)

In [34]:
df

,created_at,retweet_count,source,is_allow,user_id,user_name,user_follower_count,user_friends_count,user_verified,length_of_tweet
0,2020-10-31 14:10:28,141,Twitter for Android,True,1250294694937915394,Rumi,14,180,False,139
1,2020-10-31 14:10:11,1,Twitter for iPhone,True,57059492,Tom Bewick,2314,3002,False,140
2,2020-10-31 14:09:48,141,Twitter Web App,True,1016022678,Lemonade,285,1013,False,139
3,2020-10-31 14:09:41,141,Twitter for Android,True,1085818329816883201,The Rus,147,467,False,139
4,2020-10-31 14:09:22,0,Twitter for Android,True,1227501071490113537,Sakshi Yadav,2,24,False,140
...,...,...,...,...,...,...,...,...,...,...
47376,2020-10-30 15:29:35,0,Twitter for Android,True,1168840190426632192,neet_fad_do,254,513,False,56
47377,2020-10-30 15:29:35,1700,Twitter for Android,True,1696615807,Yarutai - Garbage NEET,23,754,False,74
47378,2020-10-30 15:28:59,167,Twitter for Android,True,1313330869113745413,Raushan,2,2,False,140
47379,2020-10-30 15:28:37,270,Twitter for Android,True,1161551282995388416,Vijaykant,140,1309,False,140
47380,2020-10-30 15:28:14,0,Twitter for Android,True,1211810532006612992,Icarus,16,45,False,139

In [37]:
df.loc[df['user_friends_count'] == df['user_friends_count'].max()]

,created_at,retweet_count,source,is_allow,user_id,user_name,user_follower_count,user_friends_count,user_verified,length_of_tweet
37873,2020-11-04 22:19:20,0,Lithium Tech.,True,15131310,Whole Foods Market,4342956,490801,True,140

In [40]:
df[df.loc[:,'source'] == 'Twitter for Android'].index

Index([    0,     3,     4,     5,     6,     7,     8,     9,    13,    14,
       ...
       47367, 47369, 47370, 47371, 47375, 47376, 47377, 47378, 47379, 47380],
      dtype='int64', length=28850)

In [44]:
df[df['user_name'] == 'Whole Foods Market']

,created_at,retweet_count,source,is_allow,user_id,user_name,user_follower_count,user_friends_count,user_verified,length_of_tweet
37873,2020-11-04 22:19:20,0,Lithium Tech.,True,15131310,Whole Foods Market,4342956,490801,True,140

In [8]:
df[df.loc[:,'source'] == 'Twitter for Android'].shape

(28850, 13)

In [10]:
df.shape

(47381, 13)

In [15]:
df.loc([df[:,'retweet_count'] == 'retweet_count' & df['source'] == 'Twitter for Android'])

InvalidIndexError: (slice(None, None, None), 'retweet_count')