In [2]:
corpus=[
    "Python is a popular programming language for machine learning and data science.",
    "Tesla's CEO is Elon Musk, a visionary entrepreneur.",
    "Barcelona and Real Madrid are two of the most famous football clubs in the world.",
    "The Great Pyramid of Giza is one of the Seven Wonders of the Ancient World.",
    "Marie Curie was a pioneering physicist and chemist who won two Nobel Prizes.",
    "Japan is known for its rich cultural heritage, including samurai warriors and cherry blossoms.",
    "The International Space Station is a habitable artificial satellite in low Earth orbit.",
    "Quantum computing is an emerging field that could revolutionize various industries.",
    "Mount Everest is the highest mountain above sea level, located in the Himalayas.",
    "Vincent van Gogh was a Dutch post-impressionist painter known for his unique style.",
    "The Great Barrier Reef is the world's largest coral reef system, located in Australia."
]

In [3]:
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer

In [4]:
cv = CountVectorizer()

In [5]:
import spacy
nlp = spacy.load("en_core_web_sm")

In [6]:
#data = nlp(corpus)

In [7]:
cv.fit(corpus)

CountVectorizer()

In [8]:
cv.vocabulary_

{'python': 72,
 'is': 43,
 'popular': 67,
 'programming': 70,
 'language': 47,
 'for': 29,
 'machine': 53,
 'learning': 49,
 'and': 3,
 'data': 19,
 'science': 80,
 'tesla': 87,
 'ceo': 10,
 'elon': 22,
 'musk': 59,
 'visionary': 95,
 'entrepreneur': 24,
 'barcelona': 7,
 'real': 74,
 'madrid': 54,
 'are': 4,
 'two': 90,
 'of': 61,
 'the': 89,
 'most': 56,
 'famous': 26,
 'football': 28,
 'clubs': 13,
 'in': 39,
 'world': 101,
 'great': 32,
 'pyramid': 71,
 'giza': 30,
 'one': 62,
 'seven': 82,
 'wonders': 100,
 'ancient': 2,
 'marie': 55,
 'curie': 18,
 'was': 97,
 'pioneering': 66,
 'physicist': 65,
 'chemist': 11,
 'who': 98,
 'won': 99,
 'nobel': 60,
 'prizes': 69,
 'japan': 45,
 'known': 46,
 'its': 44,
 'rich': 77,
 'cultural': 17,
 'heritage': 34,
 'including': 40,
 'samurai': 78,
 'warriors': 96,
 'cherry': 12,
 'blossoms': 9,
 'international': 42,
 'space': 83,
 'station': 84,
 'habitable': 33,
 'artificial': 5,
 'satellite': 79,
 'low': 52,
 'earth': 21,
 'orbit': 63,
 'quantum': 73,
 'computing': 14,
 'an': 1,
 'emerging': 23,
 'field': 27,
 'that': 88,
 'could': 16,
 'revolutionize': 76,
 'various': 93,
 'industries': 41,
 'mount': 57,
 'everest': 25,
 'highest': 35,
 'mountain': 58,
 'above': 0,
 'sea': 81,
 'level': 50,
 'located': 51,
 'himalayas': 36,
 'vincent': 94,
 'van': 92,
 'gogh': 31,
 'dutch': 20,
 'post': 68,
 'impressionist': 38,
 'painter': 64,
 'his': 37,
 'unique': 91,
 'style': 85,
 'barrier': 8,
 'reef': 75,
 'largest': 48,
 'coral': 15,
 'system': 86,
 'australia': 6}

In [9]:
len(cv.vocabulary_)

102

In [10]:
a = cv.transform(['Python is a Popular programming language Python language']).toarray()

In [11]:
a

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
        0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 1, 0, 0, 1, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [12]:
cv.inverse_transform(a)

[array(['is', 'language', 'popular', 'programming', 'python'], dtype='<U13')]

In [13]:
vector = cv.transform(corpus).toarray()

In [14]:
vector[1]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0])

In [15]:
data = pd.read_csv('emails.csv')
data.head()

                                                text  spam
0  Subject: naturally irresistible your corporate...     1
1  Subject: the stock trading gunslinger  fanny i...     1
2  Subject: unbelievable new homes made easy  im ...     1
3  Subject: 4 color printing special  request add...     1
4  Subject: do not have money , get software cds ...     1

In [17]:
data.loc[0,'text']

"Subject: naturally irresistible your corporate identity  lt is really hard to recollect a company : the  market is full of suqgestions and the information isoverwhelminq ; but a good  catchy logo , stylish statlonery and outstanding website  will make the task much easier .  we do not promise that havinq ordered a iogo your  company will automaticaily become a world ieader : it isguite ciear that  without good products , effective business organization and practicable aim it  will be hotat nowadays market ; but we do promise that your marketing efforts  will become much more effective . here is the list of clear  benefits : creativeness : hand - made , original logos , specially done  to reflect your distinctive company image . convenience : logo and stationery  are provided in all formats ; easy - to - use content management system letsyou  change your website content and even its structure . promptness : you  will see logo drafts within three business days . affordability : your  marketing break - through shouldn ' t make gaps in your budget . 100 % satisfaction  guaranteed : we provide unlimited amount of changes with no extra fees for you to  be surethat you will love the result of this collaboration . have a look at our  portfolio _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ not interested . . . _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _"

In [18]:
count = CountVectorizer()
count.fit(data.loc[:,'text'])

CountVectorizer()

In [19]:
count.vocabulary_

{'subject': 32371,
 'naturally': 23381,
 'irresistible': 18838,
 'your': 37024,
 'corporate': 10045,
 'identity': 17688,
 'lt': 21148,
 'is': 18848,
 'really': 28018,
 'hard': 16655,
 'to': 33798,
 'recollect': 28142,
 'company': 9281,
 'the': 33450,
 'market': 21665,
 'full': 15415,
 'of': 24274,
 'suqgestions': 32635,
 'and': 4836,
 'information': 18234,
 'isoverwhelminq': 18885,
 'but': 7546,
 'good': 16072,
 'catchy': 8043,
 'logo': 20960,
 'stylish': 32352,
 'statlonery': 32001,
 'outstanding': 24871,
 'website': 36080,
 'will': 36373,
 'make': 21440,
 'task': 33068,
 'much': 23052,
 'easier': 12610,
 'we': 36019,
 'do': 12048,
 'not': 23937,
 'promise': 27135,
 'that': 33441,
 'havinq': 16765,
 'ordered': 24632,
 'iogo': 18759,
 'automaticaily': 5772,
 'become': 6296,
 'world': 36633,
 'ieader': 17706,
 'it': 18913,
 'isguite': 18863,
 'ciear': 8651,
 'without': 36499,
 'products': 27033,
 'effective': 12813,
 'business': 7529,
 'organization': 24670,
 'practicable': 26619,
 'aim': 4345,
 'be': 6249,
 'hotat': 17363,
 'nowadays': 23995,
 'marketing': 21673,
 'efforts': 12830,
 'more': 22861,
 'here': 16986,
 'list': 20804,
 'clear': 8826,
 'benefits': 6430,
 'creativeness': 10282,
 'hand': 16579,
 'made': 21305,
 'original': 24695,
 'logos': 20963,
 'specially': 31581,
 'done': 12151,
 'reflect': 28298,
 'distinctive': 11932,
 'image': 17812,
 'convenience': 9896,
 'stationery': 31992,
 'are': 5274,
 'provided': 27258,
 'in': 17967,
 'all': 4518,
 'formats': 15085,
 'easy': 12623,
 'use': 35085,
 'content': 9802,
 'management': 21496,
 'system': 32876,
 'letsyou': 20553,
 'change': 8332,
 'even': 13831,
 'its': 18942,
 'structure': 32296,
 'promptness': 27155,
 'you': 37011,
 'see': 30252,
 'drafts': 12275,
 'within': 36497,
 'three': 33605,
 'days': 10839,
 'affordability': 4209,
 'break': 7158,
 'through': 33616,
 'shouldn': 30803,
 'gaps': 15569,
 'budget': 7397,
 '100': 343,
 'satisfaction': 29892,
 'guaranteed': 16380,
 'provide': 27257,
 'unlimited': 34849,
 'amount': 4756,
 'changes': 8335,
 'with': 36487,
 'no': 23796,
 'extra': 14182,
 'fees': 14514,
 'for': 15009,
 'surethat': 32650,
 'love': 21096,
 'result': 28911,
 'this': 33557,
 'collaboration': 9073,
 'have': 16757,
 'look': 21007,
 'at': 5567,
 'our': 24800,
 'portfolio': 26414,
 'interested': 18540,
 'stock': 32131,
 'trading': 34050,
 'gunslinger': 16440,
 'fanny': 14344,
 'merrill': 22235,
 'muzo': 23177,
 'colza': 9149,
 'attainder': 5629,
 'penultimate': 25558,
 'like': 20705,
 'esmark': 13671,
 'perspicuous': 25686,
 'ramble': 27802,
 'segovia': 30282,
 'group': 16321,
 'try': 34315,
 'slung': 31199,
 'kansas': 19549,
 'tanzania': 33033,
 'yes': 36959,
 'chameleon': 8316,
 'or': 24618,
 'continuant': 9826,
 'clothesman': 8910,
 'libretto': 20646,
 'chesapeake': 8482,
 'tight': 33684,
 'waterway': 35981,
 'herald': 16976,
 'hawthorn': 16771,
 'chisel': 8538,
 'morristown': 22887,
 'superior': 32581,
 'deoxyribonucleic': 11233,
 'clockwork': 8891,
 'hall': 16544,
 'incredible': 18053,
 'mcdougall': 21928,
 'hepburn': 16974,
 'einsteinian': 12889,
 'earmark': 12586,
 'sapling': 29862,
 'boar': 6850,
 'duane': 12409,
 'plain': 26081,
 'palfrey': 25102,
 'inflexible': 18204,
 'huzzah': 17551,
 'pepperoni': 25573,
 'bedtime': 6310,
 'nameable': 23283,
 'attire': 5651,
 'edt': 12764,
 'chronography': 8613,
 'optima': 24583,
 'pirogue': 26014,
 'diffusion': 11613,
 'albeit': 4437,
 'unbelievable': 34626,
 'new': 23608,
 'homes': 17264,
 'im': 17811,
 'wanting': 35894,
 'show': 30809,
 'homeowner': 17259,
 'been': 6317,
 'pre': 26666,
 'approved': 5188,
 '454': 1957,
 '169': 699,
 'home': 17250,
 'loan': 20905,
 '72': 2800,
 'fixed': 14815,
 'rate': 27875,
 'offer': 24282,
 'being': 6358,
 'extended': 14167,
 'unconditionally': 34655,
 'credit': 10291,
 'way': 35996,
 'factor': 14260,
 'take': 32965,
 'advantage': 4116,
 'limited': 20729,
 'time': 33700,
 'opportunity': 24558,
 'ask': 5444,
 'visit': 35634,
 'complete': 9345,
 'minute': 22540,
 'post': 26463,
 'approval': 5184,
 'form': 15069,
 'foward': 15174,
 'hearing': 16842,
 'from': 15334,
 'dorcas': 12180,
 'pittman': 26038,
 'color': 9129,
 'printing': 26915,
 'special': 31569,
 'request': 28731,
 'additional': 3962,
 'now': 23993,
 'click': 8852,
 'printable': 26910,
 'version': 35439,
 'order': 24631,
 'pdf': 25454,
 'format': 15082,
 'phone': 25859,
 '626': 2526,
 '338': 1519,
 '8090': 3074,
 'fax': 14435,
 '8102': 3080,
 'mail': 21367,
 'ramsey': 27813,
 'goldengraphix': 16046,
 'com': 9150,
 'golden': 16045,
 'graphix': 16200,
 '5110': 2170,
 'azusa': 5902,
 'canyon': 7826,
 'rd': 27948,
 'irwindale': 18847,
 'ca': 7615,
 '91706': 3352,
 'message': 22252,
 'an': 4791,
 'advertisement': 4127,
 'solicitation': 31375,
 'money': 22785,
 'get': 15822,
 'software': 31343,
 'cds': 8141,
 'compatibility': 9298,
 'ain': 4354,
 'great': 16223,
 'grow': 16327,
 'old': 24377,
 'along': 4585,
 'me': 22000,
 'best': 6513,
 'yet': 36966,
 'tradgedies': 34048,
 'finish': 14744,
 'by': 7585,
 'death': 10898,
 'comedies': 9173,
 'ended': 13227,
 'marriage': 21705,
 'nnews': 23793,
 'hello': 16929,
 'welcome': 36145,
 'medzonline': 22086,
 'sh': 30558,
 'groundsel': 16318,
 'op': 24502,
 'pleased': 26144,
 'introduce': 18658,
 'ourselves': 24807,
 'as': 5408,
 'one': 24445,
 'ieading': 17707,
 'online': 24462,
 'phar': 25778,
 'felicitation': 14525,
 'maceuticai': 21271,
 'shops': 30770,
 'helter': 16942,
 'shakedown': 30569,
 'cosmopolitan': 10105,
 'blister': 6791,
 'bestow': 6520,
 'ag': 4236,
 'ac': 3748,
 'tosher': 33943,
 'coadjutor': 8962,
 'va': 35173,
 'confidant': 9545,
 'um': 34586,
 'andmanyother': 4844,
 'sav': 29909,
 'inexpiable': 18175,
 'over': 24888,
 '75': 2890,
 'total': 33952,
 'confide': 9546,
 'leisure': 20490,
 'ntiaiity': 24031,
 'worldwide': 36641,
 'polite': 26301,
 'hlpplng': 17179,
 'ov': 24882,
 'allusion': 4569,
 'er': 13558,
 'miilion': 22437,
 'customers': 10558,
 '150': 625,
 'countries': 10155,
 'devitalize': 11484,
 'nice': 23683,
 'day': 10834,
 'hot': 17362,
 'play': 26126,
 'motion': 22924,
 'homeland': 17256,
 'security': 30246,
 'investments': 18709,
 'terror': 33362,
 'attacks': 5625,
 'on': 24434,
 'united': 34818,
 'states': 31979,
 'september': 30420,
 '11': 426,
 '20': 900,
 'ol': 24366,
 'changed': 8333,
 'landscape': 20208,
 'foreseeable': 15045,
 'future': 15478,
 'both': 7008,
 'physical': 25886,
 'ogica': 24334,
 'paramount': 25190,
 'industry': 18148,
 'segments': 30281,
 'especia': 13684,
 'banking': 6062,
 'nationa': 23364,
 'resource': 28847,
 'government': 16121,
 'sectors': 30233,
 'according': 3817,
 'giga': 15865,
 'who': 36298,
 'owned': 24981,
 'subsidiary': 32411,
 'forrester': 15111,
 'research': 28772,
 'woridwide': 36599,
 'demand': 11159,
 'services': 30465,
 'set': 30479,
 'eclipse': 12667,
 '46': 1974,
 '2005': 922,
 'homeiand': 17253,
 'newsietter': 23631,
 'dedicated': 10997,
 'providing': 27262,
 'readers': 27977,
 'pertaining': 25697,
 'investment': 18708,
 'opportunities': 24557,
 'lucrative': 21172,
 'sector': 30231,
 'know': 19889,
 'events': 13841,
 'related': 28460,
 'happen': 16633,
 'lightning': 20697,
 'speed': 31614,
 'what': 36233,
 'investors': 18711,
 'can': 7776,
 'position': 26434,
 'such': 32460,
 'current': 10520,
 'trends': 34200,
 'ready': 27986,
 'capitalize': 7844,
 'which': 36261,
 'heip': 16905,
 'just': 19484,
 'mind': 22493,
 'excitement': 13949,
 'present': 26792,
 'vinoble': 35575,
 'inc': 17989,
 'expected': 14050,
 'big': 6615,
 'things': 33544,
 'near': 23442,
 'ong': 24453,
 'terms': 33340,
 'symbol': 32841,
 'vnbl': 35690,
 'ob': 24127,
 'price': 26867,
 '08': 290,
 'short': 30776,
 'term': 33322,
 'target': 33049,
 '35': 1578,
 '12': 475,
 'month': 22826,
 'why': 36315,
 'believe': 6379,
 'give': 15916,
 'returns': 28976,
 'focus': 14951,
 'rfid': 29070,
 'radio': 27725,
 'frequency': 15298,
 'identification': 17680,
 'technoiogy': 33159,
 'technology': 33165,
 'uses': 35103,
 'tiny': 33739,
 'sensors': 30391,
 'transmit': 34124,
 'about': 3691,
 'person': 25663,
 'object': 24139,
 'wireiessly': 36460,
 'aiready': 4365,
 'pioneer': 25995,
 'personal': 25669,
 'location': 20925,
 'developing': 11464,
 'allows': 4561,
 'companies': 9278,
 'governments': 16123,
 'wirelessly': 36463,
 'track': 34021,
 'their': 33466,
 'assets': 5489,
 'resources': 28850,
 'has': 16717,
 'huge': 17467,
 'potentia': 26509,
 'protection': 27226,
 'transportation': 34135,
 'materiais': 21791,
 'designated': 11352,
 'high': 17081,
 'risk': 29180,
 'were': 36185,
 'they': 33530,
 'fa': 14222,
 'into': 18638,
 'wrong': 36717,
 'hands': 16601,
 'works': 36622,
 'integration': 18475,
 'two': 34445,
 'afore': 4218,
 'mentioned': 22185,
 'systems': 32881,
 'create': 10274,
 'space': 31503,
 'ocaies': 24191,
 'where': 36250,
 'deemed': 11010,
 'necessary': 23458,
 'locations': 20927,
 'may': 21863,
 'airports': 4379,
 'sea': 30153,
 'ports': 26421,
 'mines': 22507,
 'nuciear': 24042,
 'faciiities': 14242,
 'stocks': 32144,
 'news': 23624,
 'drives': 12352,
 'fresh': 15301,
 'buy': 7560,
 'malibu': 21469,
 'calif': 7697,
 'wire': 36457,
 'june': 19467,
 '16': 666,
 'oo': 24487,
 'otcbb': 24770,
 'holding': 17221,
 'seeking': 30263,
 'identify': 17685,
 'growth': 16333,
 'areas': 5276,
 'other': 24775,
 'announced': 4954,
 'today': 33814,
 'pians': 25901,
 'wiil': 36360,
 'assist': 5501,
 'automation': 5775,
 'control': 9874,
 'equipment': 13545,
 'toois': 33894,
 'processes': 27005,
 'used': 35087,
 'oi': 24343,
 'gas': 15602,
 'petrochemical': 25728,
 'industries': 18147,
 'although': 4631,
 'smail': 31207,
 'networked': 23580,
 'monitor': 22796,
 'machines': 21281,
 'detect': 11414,
 'possible': 26458,
 'problems': 26988,
 'before': 6324,
 'serious': 30444,
 'aiso': 4388,
 'deiiver': 11087,
 'safety': 29720,
 'features': 14482,
 'welis': 36155,
 'maybe': 21865,
 'trapped': 34142,
 'different': 11599,
 'ayers': 5889,
 'rock': 29327,
 'aiong': 4358,
 'water': 35969,
 'detection': 11418,
 'specific': 31587,
 'iquids': 18807,
 'operating': 24526,
 'precise': 26690,
 'opportune': 24554,
 'moment': 22766,
 'ensure': 13399,
 'certain': 8238,
 'adverse': 4123,
 'conditions': 9502,
 'occur': 24209,
 'well': 36156,
 'filiing': 14661,
 'rf': 29066,
 'based': 6150,
 'applications': 5147,
 'also': 4604,
 'safe': 29713,
 'transit': 34113,
 'only': 24463,
 'authorized': 5752,
 'handler': 16592,
 'limit': 20726,
 'entry': 13463,
 'personne': 25681,
 'ocations': 24196,
 'ensuring': 13402,
 'personnel': 25682,
 'essential': 13704,
 'should': 30799,
 'there': 33495,
 'emergency': 13094,
 'faciiity': 14243,
 'tags': 32940,
 'wouid': 36662,
 'enabie': 13178,
 'customer': 10556,
 'evaiuate': 13809,
 'empioyee': 13145,
 'danger': 10722,
 'application': 5146,
 'requires': 28744,
 'product': 27027,
 'hardware': 16669,
 'operate': 24521,
 'harsh': 16701,
 'hazardous': 16783,
 'gives': 15918,
 'valuable': 35244,
 'vita': 35652,
 'supply': 32613,
 'chain': 8290,
 'tracking': 34025,
 'chemica': 8457,
 'extraction': 14188,
 'refining': 28296,
 'saie': 29733,
 'retai': 28929,
 'evel': 13829,
 'viewpoint': 35535,
 'previousiy': 26858,
 'stated': 31976,
 'these': 33517,
 'than': 33430,
 'vaiuable': 35204,
 'too': 33892,
 'mining': 22520,
 'protective': 27228,
 'measure': 22025,
 'country': 10156,
 'natura': 23378,
 'commodities': 9247,
 'against': 4239,
 'threat': 33599,
 'preservation': 26807,
 'fueis': 15391,
 'important': 17920,
 'economy': 12697,
 'believes': 6382,
 'offering': 24286,
 'service': 30464,
 'appiication': 5133,
 'oil': 24345,
 'wil': 36361,
 'further': 15466,
 'rapidly': 27854,
 'expanding': 14037,
 'whiie': 36265,
 'taking': 32974,
 'access': 3779,
 'increasing': 18051,
 'capital': 7840,
 'gioba': 15899,
 'spending': 31634,
 'wi': 36316,
 'require': 28739,
 'goal': 16012,
 'needed': 23471,
 'cost': 10107,
 'manageable': 21494,
 'sma': 31205,
 'est': 13710,
 'businesses': 7531,
 'afford': 4208,
 'state': 31975,
 'constant': 9719,
 'potential': 26511,
 'exceptional': 13929,
 'already': 4600,
 'stands': 31927,
 'out': 24809,
 'truiy': 34299,
 'innovative': 18327,
 'happening': 16636,
 'emai': 13045,
 'contains': 9790,
 'forward': 15138,
 'looking': 21011,
 'statements': 31978,
 'meaning': 22010,
 'section': 30229,
 '27': 1207,
 'securities': 30240,
 'act': 3900,
 '1933': 819,
 '21': 972,
 'exchange': 13940,
 '1934': 820,
 'any': 5049,
 'express': 14148,
 'involve': 18738,
 'discussions': 11824,
 'respect': 28851,
 'predictions': 26711,
 'expectations': 14049,
 'beliefs': 6376,
 'projections': 27119,
 'objectives': 24145,
 'goals': 16013,
 'assumptions': 5530,
 'performance': 25603,
 'historica': 17154,
 'fact': 14258,
 'ooking': 24493,
 'estimates': 13733,
 'invoive': 18729,
 'number': 24054,
 'risks': 29205,
 'uncertainties': 34641,
 'couid': 10127,
 'cause': 8080,
 'actua': 3915,
 'results': 28916,
 'differ': 11595,
 'materia': 21789,
 'those': 33586,
 'presently': 26805,
 'anticipated': 5013,
 'action': 3904,
 'identified': 17681,
 'words': 36596,
 'projects': 27122,
 'foresee': 15043,
 'expects': 14052,
 'anticipates': 5014,
 'beiieves': 6354,
 'understands': 34716,
 'indicating': 18109,
 'actions': 3905,
 'might': 22422,
 'many': 21590,
 'micro': 22380,
 'cap': 7828,
 'factors': 14263,
 'worth': 36653,
 'noting': 23969,
 'inciude': 18006,
 'history': 17158,
 'advancing': 4114,
 'cash': 7984,
 'reiated': 28411,
 'parties': 25269,
 'shareholder': 30611,
 'unsecured': 34913,
 'basis': 6167,
 'vendor': 35375,
 'party': 25284,
 'majority': 21436,
 'stockhoider': 32137,
 'supplies': 32612,
 'ninety': 23755,
 'seven': 30501,
 'percent': 25582,
 'raw': 27913,
 'reiiance': 28421,
 'fifty': 14636,
 'numerous': 24069,
 'transactions': 34088,
 'need': 23470,
 'raise': 27770,
 'others': 24777,
 'fuily': 15401,
 'speiled': 31623,
 'sec': 30202,
 'fiiings': 14647,
 'urge': 35048,
 'read': 27973,
 'filings': 14663,
 'invest': 18694,
 'rocket': 29332,
 'report': 28674,
 'does': 12081,
 'represent': 28691,
 'contained': 9785,
 'ail': 4338,
 'facts': 14265,
 'omit': 24424,
 'material': 21792,
 'therein': 33501,
 'misleading': 22577,
 'investing': 18706,
 'must': 23165,
 'understood': 34719,
 'advice': 4134,
 'advises': 4142,
 'subscribers': 32399,
 'seek': 30259,
 'registered': 28371,
 'professiona': 27042,
 'representative': 28696,
 'deciding': 10951,
 'trade': 34033,
 'featured': 14481,
 'email': 13046,
 'none': 23862,
 'shal': 30574,
 'construed': 9746,
 'kind': 19790,
 'verge': 35408,
 'bankruptcy': 6067,
 'lose': 21058,
 'publisher': 27385,
 'advisor': 4144,
 'view': 35530,
 'herein': 16992,
 'ega': 12840,
 'tax': 33088,
 'accounting': 3826,
 'reference': 28269,
 'past': 25314,
 'speciaily': 31567,
 'seiected': 30297,
 'referenced': 28270,
 'favorabie': 14421,
 'perfect': 25593,
 'timing': 33721,
 'achieve': 3860,
 'resuits': 28910,
 'exampies': 13901,
 'given': 15917,
 'assurance': 5532,
 'remember': 28540,
 'aiways': 4393,
 'never': 23600,
 'indicative': 18112,
 'thorough': 33582,
 'due': 12419,
 'diiigence': 11631,
 'effort': 12828,
 'including': 18017,
 'review': 29015,
 'shouid': 30798,
 'completed': 9346,
 'prior': 26923,
 'compiiance': 9329,
 '17': 703,
 'discioses': 11755,
 'receipt': 28084,
 'tweive': 34428,
 'thousand': 33593,
 'doilars': 12093,
 'third': 33552,
 'gem': 15695,
 'officer': 24294,
 'director': 11703,
 'affiliate': 4193,
 'sharehoider': 30609,
 'circuiation': 8689,
 'se': 30152,
 'notice': 23957,
 'aware': 5862,
 'inherent': 18277,
 'confiict': 9569,
 'interest': 18537,
 'resuiting': 28909,
 'compensation': 9309,
 'paid': 25066,
 'conflicted': 9584,
 'al': 4417,
 'factua': 14267,
 'was': 35944,
 'gathered': 15616,
 'pubiic': 27368,
 'sources': 31479,
 'inciuding': 18008,
 'websites': 36081,
 'press': 26813,
 'releases': 28481,
 'reliabie': 28488,
 'guarantee': 16379,
 'accuracy': 3843,
 'compieteness': 9328,
 'constitutes': 9731,
 'acceptance': 3771,
 'save': 29912,
 'getting': 15826,
 'thing': 33542,
 'tried': 34228,
 'cialls': 8639,
 'cannot': 7814,
 'imagine': 17823,
 'real': 27993,
 'man': 21489,
 'bed': 6301,
 'errrectlon': 13626,
 'exactiy': 13889,
 'when': 36247,
 'want': 35892,
 'cialis': 8638,
 'lot': 21068,
 'advantages': 4118,
 'viagra': 35484,
 'effect': 12811,
 'iasts': 17619,
 '36': 1633,
 'hours': 17381,
 'start': 31955,
 '10': 342,
 'minutes': 22541,
 'mix': 22629,
 'aicohol': 4321,
 'ship': 30713,
 'right': 29143,
 'undeliverable': 34670,
 'grownups': 16331,
 'sent': 30394,
 'sun': 32541,
 'jan': 19038,
 '2001': 911,
 '09': 307,
 '24': 1097,
 '0100': 93,
 'did': 11568,
 'reach': 27959,
 'following': 14978,
 'recipient': 28122,
 'tfi': 33405,
 'kpn': 19981,
 'mon': 22771,
 '25': 1139,
 'feb': 14485,
 '2002': 917,
 '13': 528,
 '32': 1421,
 '23': 1057,
 'name': 23282,
 'recognized': 28139,
 'mts': 23048,
 'id': 17659,
 'us': 35068,
 'ptt': 27362,
 'telecom': 33198,
 'mtpi': 23047,
 '70590202251232': 2753,
 'fjt': 14822,
 'msexch': 23017,
 'ims': 17963,
 '7059': 2752,
 '000': 1,
 'co': 8956,
 'unknown': 34840,
 'lasts': 20260,
 'aicohoi': 4320,
 'las': 20243,
 'vegas': 35357,
 'rise': 29173,
 'boom': 6966,
 'fast': 14392,
 'becoming': 6298,
 'major': 21433,
 'metropolitan': 22318,
 'city': 8729,
 '60': 2452,
 'towers': 33991,
 'built': 7431,
 'around': 5348,
 'strip': 32269,
 'next': 23653,
 'years': 36946,
 '30': 1324,
 'condominiums': 9504,
 'begun': 6336,
 'first': 14782,
 'early': 12585,
 'phase': 25809,
 'construction': 9743,
 'pricing': 26878,
 'available': 5807,
 'rises': 29176,
 'trump': 34301,
 'mgm': 22342,
 'turnberry': 34395,
 'icon': 17649,
 'sky': 31114,
 'among': 4748,
 'join': 19320,
 'http': 17448,
 'www': 36774,
 'verticallv': 35446,
 'realty': 28030,
 'highrise': 17095,
 'learn': 20415,
 'comif': 9187,
 'wish': 36478,
 'excluded': 13954,
 'mailings': 21390,
 'please': 26143,
 'reply': 28666,
 'word': 36591,
 'remove': 28564,
 'line': 20749,
 'exactly': 13890,
 'ciaiis': 8636,
 'iot': 18776,
 'advantaqes': 4119,
 'riqht': 29170,
 'brighten': 7244,
 'teeth': 33177,
 'bright': 7243,
 'white': 36283,
 'considered': 9685,
 'professional': 27045,
 'whitening': 36289,
 'if': 17716,
 'so': 31302,
 'usually': 35124,
 'costs': 10117,
 ...}

In [20]:
len(count.vocabulary_)

37303

In [21]:
a = count.transform(data.loc[:,'text'])

In [22]:
a = a.toarray()

In [23]:
a

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [4, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], shape=(5728, 37303))

In [24]:
data.loc[:,'vectors'] =list(a)

In [25]:
data

,text,spam,vectors
0,Subject: naturally irresistible your corporate...,1,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
1,Subject: the stock trading gunslinger fanny i...,1,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
2,Subject: unbelievable new homes made easy im ...,1,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
3,Subject: 4 color printing special request add...,1,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
4,"Subject: do not have money , get software cds ...",1,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
...,...,...,...
5723,Subject: re : research and development charges...,0,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
5724,"Subject: re : receipts from visit jim , than...",0,"[1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
5725,Subject: re : enron case study update wow ! a...,0,"[4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
5726,"Subject: re : interest david , please , call...",0,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
5727,Subject: news : aurora 5 . 2 update aurora ve...,0,"[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."