In [2]:
import pandas as pd

In [3]:
data = pd.DataFrame({'Result':['good','bad','good','bad','excellent','good','good','excellent']})

In [4]:
data

      Result
0       good
1        bad
2       good
3        bad
4  excellent
5       good
6       good
7  excellent

In [4]:
data.Result.map({'good':2,'bad':0,'excellent':1})

0    2
1    0
2    2
3    0
4    1
5    2
6    2
7    1
Name: Result, dtype: int64

In [5]:
# Label Encoder is used to automatically set numerical value to categorical data . 
#Write Python code to convert categorical labels into numerical values using LabelEncoder.
from sklearn.preprocessing import LabelEncoder 
data1=['Cat','Eagle','Dog','Bird']
encoder = LabelEncoder()
encoded = encoder.fit_transform(data1)
print(encoded)

[1 3 2 0]

In [6]:
#Write code to convert encoded values back to original labels.
decoded = encoder.inverse_transform(encoded)
print(decoded)

['Cat' 'Eagle' 'Dog' 'Bird']

In [7]:
#Apply LabelEncoder on a dataset column using pandas.
from sklearn.preprocessing import LabelEncoder 
data2=pd.DataFrame({'Fruits':['Apple','Orange','Banana','Peach','Grapes','Watermelon']})
df = pd.DataFrame(data2)
encoder1= LabelEncoder()
df['fruits_encoded']= encoder1.fit_transform(df['Fruits'])
print(df)

       Fruits  fruits_encoded
0       Apple               0
1      Orange               3
2      Banana               1
3       Peach               4
4      Grapes               2
5  Watermelon               5

In [8]:
#Find the unique classes learned by LabelEncoder.
from sklearn.preprocessing import LabelEncoder 
data3=['Red','Blue','Pink','Blue']
encoder_1= LabelEncoder()
encoder_1.fit(data3)
print(encoder_1.classes_)

['Blue' 'Pink' 'Red']

In [9]:
import pandas as pd 
from sklearn.preprocessing import LabelEncoder
data4 = {'Names':['Mansi','Pallvi','Tania','Jatin','Divyanshu']}
df1 = pd.DataFrame(data4)
encoder2 = LabelEncoder()
df1['Names_encoded'] = encoder2.fit_transform(df1['Names'])
print(df1)

       Names  Names_encoded
0      Mansi              2
1     Pallvi              3
2      Tania              4
3      Jatin              1
4  Divyanshu              0

In [10]:
# to count number of values .
from sklearn.preprocessing import LabelEncoder 
data5 = {'Colors': 
         ['Red','Blue','Black','Orange','Blue','Black','Pink']
        }
df2 = pd.DataFrame(data5)
enorder = LabelEncoder()
counts = df2['Colors'].value_counts()
print(counts)

Colors
Blue      2
Black     2
Red       1
Orange    1
Pink      1
Name: count, dtype: int64

In [11]:
from sklearn.preprocessing import LabelEncoder
data6 = pd.DataFrame({'Name':
                      ['Mansi','Pallvi','Divyanshu','Tania','Jatin']
                     })
df5 = pd.DataFrame(data6)
enoder1 = LabelEncoder()
df5['Name_enoded'] = enoder1.fit_transform(df5['Name'])
print(df5)

        Name  Name_enoded
0      Mansi            2
1     Pallvi            3
2  Divyanshu            0
3      Tania            4
4      Jatin            1

In [14]:
df6 = pd.read_csv('used_cars_data.csv')
df6.head()

,S.No.,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,New_Price,Price
0,0,Maruti Wagon R LXI CNG,Mumbai,2010,72000,CNG,Manual,First,26.6 km/kg,998 CC,58.16 bhp,5.0,NaN,1.75
1,1,Hyundai Creta 1.6 CRDi SX Option,Pune,2015,41000,Diesel,Manual,First,19.67 kmpl,1582 CC,126.2 bhp,5.0,NaN,12.50
2,2,Honda Jazz V,Chennai,2011,46000,Petrol,Manual,First,18.2 kmpl,1199 CC,88.7 bhp,5.0,8.61 Lakh,4.50
3,3,Maruti Ertiga VDI,Chennai,2012,87000,Diesel,Manual,First,20.77 kmpl,1248 CC,88.76 bhp,7.0,NaN,6.00
4,4,Audi A4 New 2.0 TDI Multitronic,Coimbatore,2013,40670,Diesel,Automatic,Second,15.2 kmpl,1968 CC,140.8 bhp,5.0,NaN,17.74

In [13]:
df6.Transmission.value_counts()

Transmission
Manual       5204
Automatic    2049
Name: count, dtype: int64

In [18]:
from sklearn.preprocessing import LabelEncoder 
le = LabelEncoder()
a = le.fit_transform(df.loc[:,'Transmission'])

KeyError: 'Transmission'

In [6]:
from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()
encoder.fit(data.Result)

LabelEncoder()

In [7]:
encoder.transform(data.Result)

array([2, 0, 2, 0, 1, 2, 2, 1])

In [9]:
data['Label_result'] = encoder.transform(data.Result)

In [10]:
data

      Result  Label_result
0       good             2
1        bad             0
2       good             2
3        bad             0
4  excellent             1
5       good             2
6       good             2
7  excellent             1

In [11]:
encoder.classes_

array(['bad', 'excellent', 'good'], dtype=object)

In [12]:
encoder.fit_transform(data.Result)

array([2, 0, 2, 0, 1, 2, 2, 1])

In [15]:
le = LabelEncoder()
a = le.fit_transform(df6.loc[:,'Transmission'])

In [17]:
df6.insert(4,column='trans',value =a)

In [18]:
df6

,S.No.,Name,Location,Year,trans,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,New_Price,Price
0,0,Maruti Wagon R LXI CNG,Mumbai,2010,1,72000,CNG,Manual,First,26.6 km/kg,998 CC,58.16 bhp,5.0,NaN,1.75
1,1,Hyundai Creta 1.6 CRDi SX Option,Pune,2015,1,41000,Diesel,Manual,First,19.67 kmpl,1582 CC,126.2 bhp,5.0,NaN,12.50
2,2,Honda Jazz V,Chennai,2011,1,46000,Petrol,Manual,First,18.2 kmpl,1199 CC,88.7 bhp,5.0,8.61 Lakh,4.50
3,3,Maruti Ertiga VDI,Chennai,2012,1,87000,Diesel,Manual,First,20.77 kmpl,1248 CC,88.76 bhp,7.0,NaN,6.00
4,4,Audi A4 New 2.0 TDI Multitronic,Coimbatore,2013,0,40670,Diesel,Automatic,Second,15.2 kmpl,1968 CC,140.8 bhp,5.0,NaN,17.74
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7248,7248,Volkswagen Vento Diesel Trendline,Hyderabad,2011,1,89411,Diesel,Manual,First,20.54 kmpl,1598 CC,103.6 bhp,5.0,NaN,NaN
7249,7249,Volkswagen Polo GT TSI,Mumbai,2015,0,59000,Petrol,Automatic,First,17.21 kmpl,1197 CC,103.6 bhp,5.0,NaN,NaN
7250,7250,Nissan Micra Diesel XV,Kolkata,2012,1,28000,Diesel,Manual,First,23.08 kmpl,1461 CC,63.1 bhp,5.0,NaN,NaN
7251,7251,Volkswagen Polo GT TSI,Pune,2013,0,52262,Petrol,Automatic,Third,17.2 kmpl,1197 CC,103.6 bhp,5.0,NaN,NaN
7252,7252,Mercedes-Benz E-Class 2009-2013 E 220 CDI Avan...,Kochi,2014,0,72443,Diesel,Automatic,First,10.0 kmpl,2148 CC,170 bhp,5.0,NaN,NaN

In [19]:
df6.Transmission.value_counts()

Transmission
Manual       5204
Automatic    2049
Name: count, dtype: int64

In [29]:
df6

,S.No.,Name,Location,Year,trans,type_oner,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,New_Price,Price
0,0,Maruti Wagon R LXI CNG,Mumbai,2010,1,0,72000,CNG,Manual,First,26.6 km/kg,998 CC,58.16 bhp,5.0,NaN,1.75
1,1,Hyundai Creta 1.6 CRDi SX Option,Pune,2015,1,0,41000,Diesel,Manual,First,19.67 kmpl,1582 CC,126.2 bhp,5.0,NaN,12.50
2,2,Honda Jazz V,Chennai,2011,1,0,46000,Petrol,Manual,First,18.2 kmpl,1199 CC,88.7 bhp,5.0,8.61 Lakh,4.50
3,3,Maruti Ertiga VDI,Chennai,2012,1,0,87000,Diesel,Manual,First,20.77 kmpl,1248 CC,88.76 bhp,7.0,NaN,6.00
4,4,Audi A4 New 2.0 TDI Multitronic,Coimbatore,2013,0,2,40670,Diesel,Automatic,Second,15.2 kmpl,1968 CC,140.8 bhp,5.0,NaN,17.74
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7248,7248,Volkswagen Vento Diesel Trendline,Hyderabad,2011,1,0,89411,Diesel,Manual,First,20.54 kmpl,1598 CC,103.6 bhp,5.0,NaN,NaN
7249,7249,Volkswagen Polo GT TSI,Mumbai,2015,0,0,59000,Petrol,Automatic,First,17.21 kmpl,1197 CC,103.6 bhp,5.0,NaN,NaN
7250,7250,Nissan Micra Diesel XV,Kolkata,2012,1,0,28000,Diesel,Manual,First,23.08 kmpl,1461 CC,63.1 bhp,5.0,NaN,NaN
7251,7251,Volkswagen Polo GT TSI,Pune,2013,0,3,52262,Petrol,Automatic,Third,17.2 kmpl,1197 CC,103.6 bhp,5.0,NaN,NaN
7252,7252,Mercedes-Benz E-Class 2009-2013 E 220 CDI Avan...,Kochi,2014,0,0,72443,Diesel,Automatic,First,10.0 kmpl,2148 CC,170 bhp,5.0,NaN,NaN

In [35]:
from sklearn.preprocessing import OneHotEncoder
import numpy as np

data8 = np.array([['Red'], ['Blue'], ['Green']])

encoder_9 = OneHotEncoder()
encoded_7 = encoder_9.fit_transform(data8).toarray()

print(encoded_7)

[[0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]]