In [73]:
import pandas as pd
data = pd.read_csv('Housing.csv')
data.head()

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,13300000,7420,4,2,3,yes,no,no,no,yes,2,yes,furnished
1,12250000,8960,4,4,4,yes,no,no,no,yes,3,no,furnished
2,12250000,9960,3,2,2,yes,no,yes,no,no,2,yes,semi-furnished
3,12215000,7500,4,2,2,yes,no,yes,no,yes,3,yes,furnished
4,11410000,7420,4,1,2,yes,yes,yes,no,yes,2,no,furnished

In [74]:
data.isnull().sum()

price               0
area                0
bedrooms            0
bathrooms           0
stories             0
mainroad            0
guestroom           0
basement            0
hotwaterheating     0
airconditioning     0
parking             0
prefarea            0
furnishingstatus    0
dtype: int64

In [75]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 545 entries, 0 to 544
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   price             545 non-null    int64
 1   area              545 non-null    int64
 2   bedrooms          545 non-null    int64
 3   bathrooms         545 non-null    int64
 4   stories           545 non-null    int64
 5   mainroad          545 non-null    str
 6   guestroom         545 non-null    str
 7   basement          545 non-null    str
 8   hotwaterheating   545 non-null    str
 9   airconditioning   545 non-null    str
 10  parking           545 non-null    int64
 11  prefarea          545 non-null    str
 12  furnishingstatus  545 non-null    str
dtypes: int64(6), str(7)
memory usage: 55.5 KB

In [76]:
data.mainroad.value_counts()
# data.guestroom.value_counts()
# data.basement.value_counts()
# data.hotwaterheating.value_counts()
# data.prefarea.value_counts()
# data.furnishingstatus.value_counts()

mainroad
yes    468
no      77
Name: count, dtype: int64

In [77]:
data.mainroad = data.mainroad.map({'yes':1,'no':0})
data.guestroom = data.guestroom.map({'yes':1, 'no':0})
data.basement = data.basement.map({'yes':1, 'no':0})
data.hotwaterheating = data.hotwaterheating.map({'yes':1, 'no':0})
data.airconditioning = data.airconditioning.map({'yes':1, 'no':0})
data.prefarea = data.prefarea.map({'yes':1, 'no':0})

In [78]:
data

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,13300000,7420,4,2,3,1,0,0,0,1,2,1,furnished
1,12250000,8960,4,4,4,1,0,0,0,1,3,0,furnished
2,12250000,9960,3,2,2,1,0,1,0,0,2,1,semi-furnished
3,12215000,7500,4,2,2,1,0,1,0,1,3,1,furnished
4,11410000,7420,4,1,2,1,1,1,0,1,2,0,furnished
...,...,...,...,...,...,...,...,...,...,...,...,...,...
540,1820000,3000,2,1,1,1,0,1,0,0,2,0,unfurnished
541,1767150,2400,3,1,1,0,0,0,0,0,0,0,semi-furnished
542,1750000,3620,2,1,1,1,0,0,0,0,0,0,unfurnished
543,1750000,2910,3,1,1,0,0,0,0,0,0,0,furnished
544,1750000,3850,3,1,2,1,0,0,0,0,0,0,unfurnished

In [25]:
!pip install scikit-learn

Requirement already satisfied: scikit-learn in c:\users\hp\appdata\local\programs\python\python313\lib\site-packages (1.8.0)
Requirement already satisfied: numpy>=1.24.1 in c:\users\hp\appdata\local\programs\python\python313\lib\site-packages (from scikit-learn) (2.4.2)
Requirement already satisfied: scipy>=1.10.0 in c:\users\hp\appdata\local\programs\python\python313\lib\site-packages (from scikit-learn) (1.17.1)
Requirement already satisfied: joblib>=1.3.0 in c:\users\hp\appdata\local\programs\python\python313\lib\site-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.2.0 in c:\users\hp\appdata\local\programs\python\python313\lib\site-packages (from scikit-learn) (3.6.0)

[notice] A new release of pip is available: 25.2 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [66]:
from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()

In [72]:
data.loc[:,['furnishingstatus']].value_counts()

furnishingstatus
semi-furnished      227
unfurnished         178
furnished           140
Name: count, dtype: int64

In [85]:
a = encoder.fit_transform(data.loc[:,'furnishingstatus'])

In [86]:
a

array([0, 0, 1, 0, 0, 1, 1, 2, 0, 2, 0, 1, 1, 0, 1, 1, 2, 0, 0, 1, 1, 2,
       0, 0, 0, 0, 1, 1, 2, 1, 2, 1, 0, 2, 0, 0, 0, 0, 2, 1, 0, 0, 2, 1,
       0, 1, 0, 0, 2, 1, 2, 2, 0, 1, 1, 2, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0,
       0, 2, 0, 0, 1, 2, 2, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 2, 1,
       2, 0, 1, 0, 0, 1, 1, 1, 0, 1, 2, 2, 2, 2, 1, 0, 0, 2, 1, 2, 1, 1,
       1, 2, 0, 0, 0, 1, 2, 0, 0, 1, 0, 1, 1, 0, 0, 1, 2, 2, 0, 1, 2, 1,
       1, 2, 1, 2, 2, 1, 1, 0, 2, 1, 1, 2, 0, 0, 1, 1, 1, 1, 2, 1, 0, 1,
       1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 2, 2, 1, 0, 1, 1, 1, 2, 2, 2, 1,
       0, 1, 1, 1, 1, 0, 1, 1, 0, 2, 0, 1, 2, 1, 0, 1, 0, 1, 1, 1, 1, 1,
       1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 0, 1, 1, 2, 2, 1, 0, 1, 2,
       1, 1, 1, 0, 2, 1, 1, 0, 1, 1, 1, 1, 0, 2, 1, 1, 1, 1, 1, 0, 1, 1,
       0, 0, 1, 2, 1, 2, 1, 0, 1, 1, 1, 0, 1, 2, 0, 0, 1, 0, 0, 1, 1, 1,
       1, 1, 2, 1, 1, 2, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 2, 0, 2, 0, 0, 1,
       0, 2, 2, 1, 1, 2, 1, 2, 1, 1, 1, 2, 1, 0, 1, 1, 2, 0, 1, 1, 1, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 2, 2, 1, 1, 0, 1, 0, 1, 1, 1, 2, 1, 1, 0,
       2, 0, 1, 1, 0, 0, 1, 2, 1, 0, 1, 1, 0, 1, 1, 1, 1, 2, 1, 1, 1, 1,
       2, 0, 0, 0, 0, 0, 1, 2, 1, 1, 0, 1, 1, 0, 0, 2, 1, 0, 1, 1, 1, 0,
       1, 2, 1, 2, 1, 2, 1, 1, 0, 0, 0, 2, 2, 1, 2, 1, 2, 1, 1, 2, 2, 2,
       1, 0, 2, 1, 2, 2, 2, 2, 2, 2, 2, 0, 2, 2, 2, 0, 2, 2, 2, 0, 2, 0,
       2, 1, 2, 2, 2, 2, 1, 0, 0, 0, 2, 2, 2, 2, 0, 1, 1, 2, 0, 2, 1, 2,
       2, 2, 2, 2, 0, 0, 2, 1, 1, 2, 1, 1, 1, 2, 2, 2, 1, 2, 2, 2, 2, 2,
       1, 2, 1, 2, 1, 1, 1, 0, 2, 2, 1, 2, 2, 1, 2, 2, 2, 2, 1, 0, 2, 1,
       2, 2, 1, 2, 2, 1, 2, 0, 2, 0, 2, 2, 2, 2, 1, 2, 2, 2, 1, 1, 2, 2,
       2, 2, 2, 0, 2, 2, 0, 2, 1, 2, 2, 2, 2, 2, 2, 2, 0, 0, 2, 2, 2, 1,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 2, 0, 2])

In [87]:
a

array([0, 0, 1, 0, 0, 1, 1, 2, 0, 2, 0, 1, 1, 0, 1, 1, 2, 0, 0, 1, 1, 2,
       0, 0, 0, 0, 1, 1, 2, 1, 2, 1, 0, 2, 0, 0, 0, 0, 2, 1, 0, 0, 2, 1,
       0, 1, 0, 0, 2, 1, 2, 2, 0, 1, 1, 2, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0,
       0, 2, 0, 0, 1, 2, 2, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 2, 1,
       2, 0, 1, 0, 0, 1, 1, 1, 0, 1, 2, 2, 2, 2, 1, 0, 0, 2, 1, 2, 1, 1,
       1, 2, 0, 0, 0, 1, 2, 0, 0, 1, 0, 1, 1, 0, 0, 1, 2, 2, 0, 1, 2, 1,
       1, 2, 1, 2, 2, 1, 1, 0, 2, 1, 1, 2, 0, 0, 1, 1, 1, 1, 2, 1, 0, 1,
       1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 2, 2, 1, 0, 1, 1, 1, 2, 2, 2, 1,
       0, 1, 1, 1, 1, 0, 1, 1, 0, 2, 0, 1, 2, 1, 0, 1, 0, 1, 1, 1, 1, 1,
       1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 0, 1, 1, 2, 2, 1, 0, 1, 2,
       1, 1, 1, 0, 2, 1, 1, 0, 1, 1, 1, 1, 0, 2, 1, 1, 1, 1, 1, 0, 1, 1,
       0, 0, 1, 2, 1, 2, 1, 0, 1, 1, 1, 0, 1, 2, 0, 0, 1, 0, 0, 1, 1, 1,
       1, 1, 2, 1, 1, 2, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 2, 0, 2, 0, 0, 1,
       0, 2, 2, 1, 1, 2, 1, 2, 1, 1, 1, 2, 1, 0, 1, 1, 2, 0, 1, 1, 1, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 2, 2, 1, 1, 0, 1, 0, 1, 1, 1, 2, 1, 1, 0,
       2, 0, 1, 1, 0, 0, 1, 2, 1, 0, 1, 1, 0, 1, 1, 1, 1, 2, 1, 1, 1, 1,
       2, 0, 0, 0, 0, 0, 1, 2, 1, 1, 0, 1, 1, 0, 0, 2, 1, 0, 1, 1, 1, 0,
       1, 2, 1, 2, 1, 2, 1, 1, 0, 0, 0, 2, 2, 1, 2, 1, 2, 1, 1, 2, 2, 2,
       1, 0, 2, 1, 2, 2, 2, 2, 2, 2, 2, 0, 2, 2, 2, 0, 2, 2, 2, 0, 2, 0,
       2, 1, 2, 2, 2, 2, 1, 0, 0, 0, 2, 2, 2, 2, 0, 1, 1, 2, 0, 2, 1, 2,
       2, 2, 2, 2, 0, 0, 2, 1, 1, 2, 1, 1, 1, 2, 2, 2, 1, 2, 2, 2, 2, 2,
       1, 2, 1, 2, 1, 1, 1, 0, 2, 2, 1, 2, 2, 1, 2, 2, 2, 2, 1, 0, 2, 1,
       2, 2, 1, 2, 2, 1, 2, 0, 2, 0, 2, 2, 2, 2, 1, 2, 2, 2, 1, 1, 2, 2,
       2, 2, 2, 0, 2, 2, 0, 2, 1, 2, 2, 2, 2, 2, 2, 2, 0, 0, 2, 2, 2, 1,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 2, 0, 2])

In [95]:
data.loc[:,'furnishingstatus_new'] = a

In [96]:
data.drop('furnishingstatus',axis=1, inplace=True)

In [99]:
data.loc[:,'furnishingstatus_new'].value_counts()

furnishingstatus_new
1    227
2    178
0    140
Name: count, dtype: int64

In [100]:
#independent and dependent variables
x= data.iloc[:,1:]
y= data.loc[:,'price']
y

0      13300000
1      12250000
2      12250000
3      12215000
4      11410000
         ...
540     1820000
541     1767150
542     1750000
543     1750000
544     1750000
Name: price, Length: 545, dtype: int64

In [101]:
from sklearn.model_selection import train_test_split

In [102]:
x_train, x_test, y_train, y_test=train_test_split(x,y, test_size=0.3, random_state = 10)

In [103]:
x_train

,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus_new
175,9800,4,2,2,1,1,0,0,0,2,0,1
25,6540,4,2,2,1,1,1,0,1,2,1,0
253,3520,2,1,2,1,0,0,0,0,0,1,0
257,8250,3,1,1,1,0,0,0,0,0,0,0
431,3180,4,1,2,1,0,1,0,1,0,0,2
...,...,...,...,...,...,...,...,...,...,...,...,...
369,3600,2,1,1,1,0,0,0,0,0,0,0
320,4320,3,1,2,1,0,0,0,0,2,1,0
527,1836,2,1,1,0,0,1,0,0,0,0,1
125,15600,3,1,1,1,0,0,0,1,2,0,1
265,2880,3,1,2,1,0,0,0,0,0,1,1

In [104]:
y_train

175    5250000
25     8540000
253    4515000
257    4480000
431    3290000
        ...
369    3675000
320    4060000
527    2275000
125    5943000
265    4403000
Name: price, Length: 381, dtype: int64

In [105]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()

In [106]:
model.fit(x_train, y_train)

LinearRegression()

In [107]:
y_pred= model.predict(x_test)

In [108]:
y_pred

array([ 2702410.15229689,  3695854.83891825,  5982928.90643947,
        3849622.96031104,  6577424.27942361,  6942792.0206936 ,
        3613197.26429001,  3132304.09319921,  5388596.85044232,
        3164667.47369529,  5049051.75477786,  2199488.50364451,
        4219668.55289418,  4542712.11927192,  6729357.63055869,
        2687702.03178332,  7339582.23136245,  6358881.79610238,
        5139522.31850371,  4309297.83430755,  2624652.0585695 ,
        2023396.2986943 ,  5839227.33101739,  5418125.61030145,
        6753758.09892638,  6100162.54389682,  3676404.43273967,
        3734109.77975708,  3623128.08654447,  3785902.00975955,
        4455888.49095388,  5017126.87408339,  5545504.52295889,
        5531315.20489811,  7496365.28201806,  5117086.89560122,
        6672751.46490915,  2381679.84884597,  5305624.34592427,
        5494095.82596319,  4990323.49274269,  5265040.94515175,
        2946623.78627304,  6470284.76966086,  5812675.93623503,
        7879075.85666001,  8334082.21075059,  6101069.78130315,
        3620550.36304258,  4939541.90059087,  3297000.05030046,
        6031345.10152519,  3967399.49586028,  4806121.3419478 ,
        2896684.15449259,  5670204.76549962,  5307441.51953552,
        3584135.67871802,  3785479.84980349,  4634930.84631217,
        4572896.95151656,  4765613.69054512,  5197256.04766552,
        3734815.20230315,  4175032.21705221,  6833056.09286382,
        3135953.66267791,  2597398.61887052,  2515353.44860041,
        7119637.0549887 ,  4104002.34070861,  6457056.07343126,
        6218330.64419135,  3697019.86051927,  2818874.28872236,
        3372289.02795778,  3299356.48383519,  5084750.6754484 ,
        9696042.23670341,  4812265.12708902,  7365633.04396154,
        5166706.14334821,  3763691.45669231,  2796028.96999423,
        4549225.11425081,  2607027.64107556,  5061232.17337391,
       10453090.87621601,  5808906.10353641,  3165500.3478523 ,
        5616964.47228606,  3307802.58127607,  6378985.62722027,
        6124240.73183159,  3996483.30415043,  3530449.7598756 ,
        3336914.23951848,  6678796.61465447,  4825385.57462315,
        5010719.91386797,  5332657.49812817,  4024995.62519809,
        4516817.15045431,  4447755.24252588,  6905096.22681663,
        4200507.37609274,  4053427.34931589,  3257477.35211439,
        5870927.48639982,  2860802.38177471,  4395332.47556027,
        5041237.89394855,  3875193.31676651,  2822010.26864019,
        2891119.31657545,  5488477.10504094,  3364923.36386146,
        2263317.23891977,  4980993.65812667,  4637431.96092375,
        7625660.46586454,  4355626.22353058,  4818517.61909958,
        4091208.76612365,  7445724.73902299,  3432395.38613569,
        4988594.53951902,  4750562.9456185 ,  5403787.30314765,
        4483420.82828601,  5009987.36009959,  5122790.24201138,
        6574656.8330985 ,  4525582.95110775,  3408366.8092985 ,
        4662611.83059841,  4601625.42338175,  3112302.5897488 ,
        7143347.56489275,  4973864.27936458,  5369576.30026744,
        8726715.34811778,  6106437.79428456,  3482144.35552009,
        3587756.61080937,  6931561.44001061,  6720145.48382896,
        4296609.23483627,  6101025.42818063,  4467053.24124283,
        3905887.72348409,  3394600.04435181,  3877541.56448535,
        6429241.60976105,  7795146.76623616,  3044830.56747457,
        3739052.20617547,  4483303.85527428,  3116672.86676638,
        8082395.63954723,  6460501.13550163,  4082136.79566617,
        5661354.88795816,  5817704.04682235])

In [109]:
from sklearn.metrics import r2_score
r2_score(y_test, y_pred)

0.742384108045443

In [110]:
from sklearn.metrics import mean_squared_error

mse = mean_squared_error(y_test, y_pred)
print('MSE:', mse)

MSE: 751121857487.2773

In [111]:
import joblib
joblib.dump(model, 'housing.pkl')

['housing.pkl']

In [112]:
data.to_csv('converted.csv')

In [114]:
import joblib 
house = joblib.load('housing.pkl')
house.predict([[9960,4,2,3,1,0,1,0,1,2,1,0]])

C:\Users\hp\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([9403962.03642794])

In [116]:
!pip install kagglehub

Collecting kagglehub
  Downloading kagglehub-1.0.0-py3-none-any.whl.metadata (40 kB)
Collecting kagglesdk<1.0,>=0.1.14 (from kagglehub)
  Downloading kagglesdk-0.1.16-py3-none-any.whl.metadata (13 kB)
Requirement already satisfied: packaging in c:\users\hp\appdata\local\programs\python\python313\lib\site-packages (from kagglehub) (26.0)
Requirement already satisfied: pyyaml in c:\users\hp\appdata\local\programs\python\python313\lib\site-packages (from kagglehub) (6.0.3)
Requirement already satisfied: requests in c:\users\hp\appdata\local\programs\python\python313\lib\site-packages (from kagglehub) (2.32.5)
Collecting tqdm (from kagglehub)
  Downloading tqdm-4.67.3-py3-none-any.whl.metadata (57 kB)
Collecting protobuf (from kagglesdk<1.0,>=0.1.14->kagglehub)
  Downloading protobuf-7.34.0-cp310-abi3-win_amd64.whl.metadata (595 bytes)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\hp\appdata\local\programs\python\python313\lib\site-packages (from requests->kagglehub) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in c:\users\hp\appdata\local\programs\python\python313\lib\site-packages (from requests->kagglehub) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\hp\appdata\local\programs\python\python313\lib\site-packages (from requests->kagglehub) (2.6.3)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\hp\appdata\local\programs\python\python313\lib\site-packages (from requests->kagglehub) (2026.1.4)
Requirement already satisfied: colorama in c:\users\hp\appdata\local\programs\python\python313\lib\site-packages (from tqdm->kagglehub) (0.4.6)
Downloading kagglehub-1.0.0-py3-none-any.whl (70 kB)
Downloading kagglesdk-0.1.16-py3-none-any.whl (160 kB)
Downloading protobuf-7.34.0-cp310-abi3-win_amd64.whl (437 kB)
Downloading tqdm-4.67.3-py3-none-any.whl (78 kB)
Installing collected packages: tqdm, protobuf, kagglesdk, kagglehub

   ---------------------------------------- 0/4 [tqdm]
   ---------------------------------------- 0/4 [tqdm]
   ---------------------------------------- 0/4 [tqdm]
   ---------------------------------------- 0/4 [tqdm]
   ---------------------------------------- 0/4 [tqdm]
   ---------------------------------------- 0/4 [tqdm]
   ---------------------------------------- 0/4 [tqdm]
   ---------------------------------------- 0/4 [tqdm]
   ---------------------------------------- 0/4 [tqdm]
   ---------------------------------------- 0/4 [tqdm]
   ---------- ----------------------------- 1/4 [protobuf]
   ---------- ----------------------------- 1/4 [protobuf]
   ---------- ----------------------------- 1/4 [protobuf]
   ---------- ----------------------------- 1/4 [protobuf]
   ---------- ----------------------------- 1/4 [protobuf]
   ---------- ----------------------------- 1/4 [protobuf]
   ---------- ----------------------------- 1/4 [protobuf]
   ---------- ----------------------------- 1/4 [protobuf]
   ---------- ----------------------------- 1/4 [protobuf]
   ---------- ----------------------------- 1/4 [protobuf]
   ---------- ----------------------------- 1/4 [protobuf]
   ---------- ----------------------------- 1/4 [protobuf]
   ---------- ----------------------------- 1/4 [protobuf]
   ---------- ----------------------------- 1/4 [protobuf]
   ---------- ----------------------------- 1/4 [protobuf]
   ---------- ----------------------------- 1/4 [protobuf]
   ---------- ----------------------------- 1/4 [protobuf]
   ---------- ----------------------------- 1/4 [protobuf]
   ---------- ----------------------------- 1/4 [protobuf]
   -------------------- ------------------- 2/4 [kagglesdk]
   -------------------- ------------------- 2/4 [kagglesdk]
   -------------------- ------------------- 2/4 [kagglesdk]
   -------------------- ------------------- 2/4 [kagglesdk]
   -------------------- ------------------- 2/4 [kagglesdk]
   -------------------- ------------------- 2/4 [kagglesdk]
   -------------------- ------------------- 2/4 [kagglesdk]
   -------------------- ------------------- 2/4 [kagglesdk]
   -------------------- ------------------- 2/4 [kagglesdk]
   -------------------- ------------------- 2/4 [kagglesdk]
   -------------------- ------------------- 2/4 [kagglesdk]
   -------------------- ------------------- 2/4 [kagglesdk]
   -------------------- ------------------- 2/4 [kagglesdk]
   -------------------- ------------------- 2/4 [kagglesdk]
   -------------------- ------------------- 2/4 [kagglesdk]
   -------------------- ------------------- 2/4 [kagglesdk]
   -------------------- ------------------- 2/4 [kagglesdk]
   -------------------- ------------------- 2/4 [kagglesdk]
   -------------------- ------------------- 2/4 [kagglesdk]
   -------------------- ------------------- 2/4 [kagglesdk]
   -------------------- ------------------- 2/4 [kagglesdk]
   -------------------- ------------------- 2/4 [kagglesdk]
   -------------------- ------------------- 2/4 [kagglesdk]
   ------------------------------ --------- 3/4 [kagglehub]
   ------------------------------ --------- 3/4 [kagglehub]
   ------------------------------ --------- 3/4 [kagglehub]
   ------------------------------ --------- 3/4 [kagglehub]
   ------------------------------ --------- 3/4 [kagglehub]
   ------------------------------ --------- 3/4 [kagglehub]
   ------------------------------ --------- 3/4 [kagglehub]
   ------------------------------ --------- 3/4 [kagglehub]
   ------------------------------ --------- 3/4 [kagglehub]
   ---------------------------------------- 4/4 [kagglehub]

Successfully installed kagglehub-1.0.0 kagglesdk-0.1.16 protobuf-7.34.0 tqdm-4.67.3

[notice] A new release of pip is available: 25.2 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

import kagglehub

In [118]:
path = kagglehub.dataset_download("yasserh/housing-prices-dataset')

SyntaxError: unterminated string literal (detected at line 1) (992215303.py, line 1)